// GENERATED by products/wpforms/qc/make-fragment.mjs — source capture: site:qc/render/coupon-codes.php (read-only plugin render) (json).
// A fragment of a same-build capture, shared so a standalone download has it (director 2026-10-06, R6).
(window.WPF_FRAGMENTS = window.WPF_FRAGMENTS || {})["coupon-codes"] = {"source":"site:qc/render/coupon-codes.php (read-only plugin render)","data":{"data":["PSE7B3AU","MHZ565MQ","25WXCSKE","J6FEQTQM","CSQY4FZW","CHU6JEYJ","J8G27PS9","UVQPGSHY"]}};
