// GENERATED by products/wpforms/qc/make-fragment.mjs — source capture: site:qc/render/keyword-list.php (read-only plugin render) (json).
// A fragment of a same-build capture, shared so a standalone download has it (director 2026-10-06, R6).
(window.WPF_FRAGMENTS = window.WPF_FRAGMENTS || {})["keyword-list"] = {"source":"site:qc/render/keyword-list.php (read-only plugin render)","data":{"keywords":["earn extra cash","free membership","search engine optimization","more internet traffic","click to download"]}};
