/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for wpvibe.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 * Rebuild after every capture batch: node tools/build-snap-nav.js wpvibe
 */
window.__snapNav = {
  "p": "wpvibe",
  "k": {
    "admin.php?action=edit&id=35&page=wc-orders": "admin-wc-order-single",
    "admin.php?form_id=31&page=wpforms-builder&view=fields": "admin-wpforms-builder-cake-order",
    "admin.php?form_id=56&page=wpforms-builder&view=fields": "admin-wpforms-builder-run",
    "admin.php?page=aioseo": "admin-aioseo-dashboard-default",
    "admin.php?page=botiga-dashboard": "admin-botiga-dashboard-default",
    "admin.php?page=botiga-dashboard&tab=settings": "admin-botiga-settings-ai-mcp-off",
    "admin.php?page=duplicator": "admin-duplicator-backups-empty",
    "admin.php?page=vibe-ai": "admin-wpvibe-page-not-connected",
    "admin.php?page=vibe-ai-activity": "admin-wpvibe-approval-log-empty",
    "admin.php?page=wc-admin": "admin-wc-setup-wizard",
    "admin.php?page=wc-admin&path=/setup-wizard": "admin-wc-setup-wizard",
    "admin.php?page=wc-orders": "admin-wc-orders-one",
    "admin.php?page=wc-orders&status=all": "admin-wc-orders-one",
    "admin.php?page=wc-settings": "admin-wc-settings-general-default",
    "admin.php?page=wc-settings&section=&tab=products": "admin-wc-settings-products",
    "admin.php?page=wc-settings&section=&tab=shipping": "admin-wc-settings-shipping-default",
    "admin.php?page=wc-settings&section=standard&tab=tax": "admin-wc-settings-tax-configured",
    "admin.php?page=wc-settings&section=stripe&tab=checkout": "admin-wc-stripe-keys-empty",
    "admin.php?page=wc-settings&tab=checkout": "admin-wc-settings-payments-default",
    "admin.php?page=wc-settings&tab=email": "admin-wc-settings-emails",
    "admin.php?page=wc-settings&tab=general": "admin-wc-settings-general-default",
    "admin.php?page=wc-settings&tab=products": "admin-wc-settings-products",
    "admin.php?page=wc-settings&tab=shipping": "admin-wc-settings-shipping-default",
    "admin.php?page=wc-settings&tab=tax": "admin-wc-settings-tax-configured",
    "admin.php?page=wp-mail-smtp": "admin-wp-mail-smtp-settings-default",
    "admin.php?page=wp-mail-smtp&tab=settings": "admin-wp-mail-smtp-settings-default",
    "admin.php?page=wp-mail-smtp-setup-wizard&type=local#/step/choose_mailer": "admin-wp-mail-smtp-wizard-choose-mailer",
    "admin.php?page=wpcode": "admin-wpcode-snippets-empty",
    "admin.php?page=wpcode&view=all": "admin-wpcode-snippets-empty",
    "admin.php?page=wpconsent": "admin-wpconsent-default",
    "admin.php?page=wpforms-builder": "admin-wpforms-builder-run",
    "admin.php?page=wpforms-overview": "admin-wpforms-setup-wizard",
    "admin.php?page=wpforms-tools": "admin-wpforms-tools-ai-mcp-off",
    "admin.php?page=wpforms-tools&view=ai-mcp": "admin-wpforms-tools-ai-mcp-off",
    "authorize-application.php?app_id=01965f3a-7b2d-7000-8000-000000000001&app_name=WPVibe (sullie@bakery.example.com) · Sep 19, 2026, 23:46:11 UTC&success_url=https://mcp.wpvibe.ai/auth/wp-callback?state=4b8e1bfe-5325-4534-9970-9a698a3a188d&wpvibe_preserve_proof=1": "admin-authorize-application-wpvibe",
    "cart": "frontend-bakery-cart-run",
    "classic-vanilla-celebration": "frontend-bakery-product",
    "contact-us": "frontend-bakery-about",
    "edit.php": "admin-posts-fresh",
    "edit.php?post_status=trash&post_type=post": "admin-posts-trashed",
    "edit.php?post_type=page": "admin-pages-fresh",
    "edit.php?post_type=post": "admin-posts-fresh",
    "edit.php?post_type=product": "admin-wc-products-empty",
    "edit.php?post_type=shop_coupon": "admin-wc-coupons-launch",
    "index.php?add-to-cart=45": "frontend-bakery-add-to-cart",
    "index.php?add-to-cart=49": "frontend-bakery-add-to-cart-run",
    "index.php?page=aioseo-setup-wizard": "admin-aioseo-setup-wizard",
    "nav-menus.php": "admin-menus-bakery",
    "op_cb961117df674167?t=bkzU5Y_gDWl6wmtPjB2JIHcZSqREFEdImvHd7ZxClsg": "wpvibe-approval",
    "options-general.php": "admin-settings-general-fresh",
    "options-permalink.php": "admin-settings-permalinks-fresh",
    "options-reading.php": "admin-settings-reading-fresh",
    "order-cakes": "frontend-bakery-order-cakes",
    "plugin-install.php": "admin-plugin-install-wpvibe",
    "plugin-install.php?s=wpvibe&tab=search&type=term": "admin-plugin-install-wpvibe",
    "plugin-install.php?tab=search": "admin-plugin-install-wpvibe",
    "plugins.php": "admin-plugins-list-fresh",
    "plugins.php?plugin_status=all": "admin-plugins-list-fresh",
    "red-velvet": "frontend-bakery-product-run",
    "shop": "frontend-bakery-shop",
    "themes.php": "admin-themes-fresh",
    "wp-admin": "admin-wp-dashboard-fresh"
  },
  "v": {
    "admin.php?page=botiga-dashboard": [
      "tab"
    ],
    "admin.php?page=wc-admin": [
      "path"
    ],
    "admin.php?page=wc-orders": [
      "action",
      "id",
      "status"
    ],
    "admin.php?page=wc-settings": [
      "section",
      "tab"
    ],
    "admin.php?page=wp-mail-smtp": [
      "tab"
    ],
    "admin.php?page=wp-mail-smtp-setup-wizard": [
      "type"
    ],
    "admin.php?page=wpcode": [
      "view"
    ],
    "admin.php?page=wpforms-builder": [
      "form_id",
      "view"
    ],
    "admin.php?page=wpforms-tools": [
      "view"
    ],
    "authorize-application.php": [
      "app_id",
      "app_name",
      "success_url",
      "wpvibe_preserve_proof"
    ],
    "edit.php": [
      "post_status",
      "post_type"
    ],
    "index.php": [
      "add-to-cart"
    ],
    "op_cb961117df674167": [
      "t"
    ],
    "plugin-install.php": [
      "s",
      "tab",
      "type"
    ],
    "plugins.php": [
      "plugin_status"
    ]
  }
};
