/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for optinmonster-app.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 * Rebuild after every capture batch: node tools/build-snap-nav.js optinmonster-app
 */
window.__snapNav = {
  "p": "optinmonster-app",
  "k": {
    "6ab81dcd84a45": "app-campaigns-site",
    "6ab82086ea996": "app-campaigns-folder",
    "a3bnrrvujqyqkrh6crzb": "app-campaigns-campaign",
    "account": "app-account",
    "analytics": "app-campaign-analytics",
    "archives": "app-campaigns-folder-archives",
    "campaigns": "app-campaigns",
    "dashboard": "app-dashboard",
    "edit": "app-builder-design",
    "edit#/analytics/": "app-builder-analytics",
    "edit#/publish/": "app-builder-publish",
    "edit#/publish/#schedule": "app-builder-publish--schedule",
    "edit#/rulesets/": "app-builder-display-rules",
    "leads": "app-leads",
    "new": "app-new-campaign",
    "new?campaignType=popup": "app-new-campaign--favorites",
    "new?campaignType=popup&template=popup-basic-dark-production": "app-new-campaign--name-modal",
    "sites": "app-sites",
    "support": "app-support",
    "tjrnkuhbdzfebjblahxo": "app-campaigns--split",
    "trash": "app-campaigns-folder-trash"
  },
  "v": {
    "new": [
      "campaignType",
      "template"
    ]
  }
};
