/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for wpforms.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 *   r  nav rules from products/wpforms/nav-rules.json (applied to every key)
 * Rebuild after every capture batch: node tools/build-snap-nav.js wpforms
 */
window.__snapNav = {
  "p": "wpforms",
  "k": {
    "1": "gmail-inbox-dummy",
    "%20middleware)": "google-oauth-signin",
    "ChatGPT%20(08_09_2026%2006%EF%BC%9A44%EF%BC%9A11).html)": "chatgpt-new-chat",
    "New%20chat%20-%20Claude.html)": "claude-new-chat",
    "admin.php?entry_id=5&page=wpforms-entries&view=details": "admin-entry-detail",
    "admin.php?entry_id=7530&page=wpforms-entries&view=details": "admin-entry-detail-smarttags",
    "admin.php?entry_id=7829&page=wpforms-entries&view=details": "admin-entry-detail--pdf",
    "admin.php?entry_id=7829&page=wpforms-entries&view=edit": "admin-entry-edit",
    "admin.php?entry_id=7829&page=wpforms-entries&view=print": "admin-entry-print",
    "admin.php?form_id=100&page=wpforms-entries&view=list": "admin-entries-list-100",
    "admin.php?form_id=110&page=wpforms-entries&view=list": "admin-entries-list-110",
    "admin.php?form_id=141&page=wpforms-builder": "notifications",
    "admin.php?form_id=141&page=wpforms-builder&section=notifications&view=settings": "builder-settings-notifications-cl",
    "admin.php?form_id=144&page=wpforms-builder&view=fields": "builder-field-options-likert_scale",
    "admin.php?form_id=147&page=wpforms-builder&view=fields": "builder-field-options-net_promoter_score",
    "admin.php?form_id=1725&page=wpforms-builder&section=confirmation&view=settings": "builder-settings-confirmation--pdf-smarttags",
    "admin.php?form_id=1725&page=wpforms-builder&section=notifications&view=settings": "builder-settings-notifications--pdf-smarttags",
    "admin.php?form_id=1725&page=wpforms-entries&status=trash&view=list": "admin-entries-list-1725--trash",
    "admin.php?form_id=1725&page=wpforms-entries&type=starred&view=list": "admin-entries-list-1725--starred",
    "admin.php?form_id=1725&page=wpforms-entries&type=unread&view=list": "admin-entries-list-1725--unread",
    "admin.php?form_id=1725&page=wpforms-entries&view=list": "admin-entries-list-1725",
    "admin.php?form_id=1759&page=wpforms-builder&view=fields": "builder-mercado-pago-field",
    "admin.php?form_id=1779&page=wpforms-builder&view=settings": "builder-settings-general",
    "admin.php?form_id=1779&page=wpforms-entries&view=list": "admin-entries-ranking-results",
    "admin.php?form_id=1779&page=wpforms-entries&view=survey": "sp-results-ranking-full",
    "admin.php?form_id=1882&page=wpforms-builder&view=fields": "builder-job-application-final",
    "admin.php?form_id=191&page=wpforms-entries&view=list": "admin-entries-list-191",
    "admin.php?form_id=1965&page=wpforms-builder&view=fields": "builder-photography-quote",
    "admin.php?form_id=2280&page=wpforms-builder&view=fields": "builder-field-options-content-visual",
    "admin.php?form_id=2576&page=wpforms-builder&view=fields": "builder-fields-quiz",
    "admin.php?form_id=2579&page=wpforms-builder&view=fields": "builder-fields-lead_forms",
    "admin.php?form_id=2579&page=wpforms-builder&view=settings": "builder-settings-lead_forms--on",
    "admin.php?form_id=2582&page=wpforms-builder&view=settings": "builder-settings-user_registration--login",
    "admin.php?form_id=2586&page=wpforms-builder&view=settings": "builder-settings-user_registration--reset",
    "admin.php?form_id=2591&page=wpforms-builder&view=settings": "builder-settings-user_registration--register",
    "admin.php?form_id=2594&page=wpforms-builder&view=settings": "builder-settings-form_pages--on",
    "admin.php?form_id=2620&page=wpforms-builder&view=settings": "builder-settings-post_submissions--on",
    "admin.php?form_id=2629&page=wpforms-builder&view=settings": "builder-settings-wpf_sc_settings--on",
    "admin.php?form_id=2652&page=wpforms-builder&view=settings": "builder-settings-quiz--personality",
    "admin.php?form_id=2654&page=wpforms-builder&view=settings": "builder-settings-quiz--weighted",
    "admin.php?form_id=2680&page=wpforms-builder&section=pdf&view=settings": "builder-settings-pdf--empty",
    "admin.php?form_id=32&page=wpforms-entries&view=list": "admin-entries-list",
    "admin.php?form_id=36&page=wpforms-builder&section=themes&view=settings": "builder-settings-themes",
    "admin.php?form_id=40&page=wpforms-builder&view=fields": "builder-calculation-editor-active",
    "admin.php?form_id=401&page=wpforms-builder&section=notifications&view=settings": "builder-settings-notifications",
    "admin.php?form_id=401&page=wpforms-builder&view=fields": "builder-embed-modal",
    "admin.php?form_id=401&page=wpforms-builder&view=payments": "builder-payments",
    "admin.php?form_id=401&page=wpforms-builder&view=revisions": "builder-revisions",
    "admin.php?form_id=401&page=wpforms-builder&view=setup": "builder-setup",
    "admin.php?form_id=406&page=wpforms-builder&view=fields": "builder-406-field-advanced-css",
    "admin.php?form_id=406&page=wpforms-entries&status=spam&view=list": "admin-entries-spam",
    "admin.php?mode=test&page=wpforms-payments&payment_id=2&view=single": "admin-payment-detail-mercado-pago",
    "admin.php?page=wpforms-entries": "admin-entries-overview",
    "admin.php?page=wpforms-payments&payment_id=1&view=payment": "admin-payment-detail",
    "admin.php?page=wpforms-payments&status=publish&view=coupons": "admin-payments-coupons",
    "admin.php?page=wpforms-payments&view=coupon": "admin-payments-coupons-add-new",
    "admin.php?page=wpforms-payments&view=coupons": "admin-payments-coupons",
    "admin.php?page=wpforms-settings&view=access": "admin-settings-access",
    "admin.php?page=wpforms-settings&view=captcha": "admin-settings-captcha",
    "admin.php?page=wpforms-settings&view=email": "admin-settings-email",
    "admin.php?page=wpforms-settings&view=general": "admin-settings-general",
    "admin.php?page=wpforms-settings&view=geolocation": "admin-settings-geolocation",
    "admin.php?page=wpforms-settings&view=misc": "admin-settings-misc",
    "admin.php?page=wpforms-settings&view=payments": "admin-settings-payments",
    "admin.php?page=wpforms-settings&view=validation": "admin-settings-validation",
    "admin.php?page=wpforms-templates": "admin-templates",
    "admin.php?page=wpforms-tools&s=wpforms&view=action-scheduler": "admin-tools-action-scheduler",
    "admin.php?page=wpforms-tools&status=all&view=entry-automation": "admin-tools-entry-automation",
    "admin.php?page=wpforms-tools&tab=entries&view=export": "admin-tools-export",
    "admin.php?page=wpforms-tools&tab=entries&view=import": "admin-tools-import-entries",
    "admin.php?page=wpforms-tools&tab=templates&view=export": "admin-tools-export-templates",
    "admin.php?page=wpforms-tools&view=action-scheduler": "admin-tools-action-scheduler",
    "admin.php?page=wpforms-tools&view=ai-mcp": "admin-tools-ai-mcp",
    "admin.php?page=wpforms-tools&view=entry-automation": "admin-tools-entry-automation",
    "admin.php?page=wpforms-tools&view=export": "admin-tools-export",
    "admin.php?page=wpforms-tools&view=import": "admin-tools-import",
    "admin.php?page=wpforms-tools&view=logs": "admin-tools-logs",
    "admin.php?page=wpforms-tools&view=system": "admin-tools-system",
    "admin.php?page=wpforms-tools&view=wpcode": "admin-tools-code-snippets",
    "admin.php?page=wpforms-wpconsent": "admin-privacy-compliance",
    "bakery-chat": "frontend-conversational-form",
    "catering-quote": "frontend-form-page",
    "catering-quote-classic": "frontend-form-page--classic",
    "catering-request": "frontend-catering-prefilled",
    "cider-tasting-rsvp": "frontend-form-locker--age",
    "custom-order-inquiry": "frontend-offline-form--offline",
    "customize.php?autofocus[section]=custom_css": "admin-customizer-additional-css",
    "dashboard": "klaviyo-dashboard",
    "holiday-pie-preorder": "frontend-form-locker--entry-limit",
    "index.php?entry=7829&snap_pdf_output=certificate-classic": "pdf-output--certificate-classic",
    "index.php?entry=7829&snap_pdf_output=certificate-elegant": "pdf-output--certificate-elegant",
    "index.php?entry=7829&snap_pdf_output=certificate-modern": "pdf-output--certificate-modern",
    "index.php?entry=7829&snap_pdf_output=document-application": "pdf-output--document-application",
    "index.php?entry=7829&snap_pdf_output=document-basic": "pdf-output--document-basic",
    "index.php?entry=7829&snap_pdf_output=document-coverpage": "pdf-output--document-coverpage",
    "index.php?entry=7829&snap_pdf_output=document-legal": "pdf-output--document-legal",
    "index.php?entry=7829&snap_pdf_output=document-sidebar": "pdf-output--document-sidebar",
    "index.php?entry=7829&snap_pdf_output=document-table": "pdf-output--document-table",
    "index.php?entry=7829&snap_pdf_output=financial-classic": "pdf-output--financial-classic",
    "index.php?entry=7829&snap_pdf_output=financial-modern": "pdf-output--financial-modern",
    "index.php?entry=7829&snap_pdf_output=financial-sidebar": "pdf-output--financial-sidebar",
    "index.php?entry=7829&snap_pdf_output=notification-classic": "pdf-output--notification-classic",
    "index.php?entry=7829&snap_pdf_output=notification-compact": "pdf-output--notification-compact",
    "index.php?entry=7829&snap_pdf_output=notification-elegant": "pdf-output--notification-elegant",
    "index.php?entry=7829&snap_pdf_output=notification-modern": "pdf-output--notification-modern",
    "index.php?entry=7829&snap_pdf_output=notification-tech": "pdf-output--notification-tech",
    "index.php?p=2622&preview=true": "frontend-post-submission-post",
    "index.php?wpforms_form_preview=1759": "frontend-mercado-pago-field",
    "index.php?wpforms_form_preview=1882": "frontend-job-application-preview",
    "index.php?wpforms_form_preview=1965": "frontend-photography-quote",
    "index.php?wpforms_form_preview=2289": "frontend-repeater-blocks",
    "index.php?wpforms_form_preview=2659": "frontend-multipage--circles",
    "index.php?wpforms_pdf_download=demo-pdf-download-token": "frontend-pdf-access--password",
    "join-the-bakery-club": "frontend-user-register",
    "know-your-bakes": "frontend-quiz",
    "know-your-bakes?snap_entry=8019&wpforms_return=demo-return-token": "frontend-quiz--result",
    "master-form-embedded": "frontend-published-form",
    "member-area": "frontend-user-login--logged-in",
    "member-login": "frontend-user-login",
    "members-price-list": "frontend-form-locker--email",
    "new": "claude-new-chat",
    "next-pastry-poll": "frontend-poll-results",
    "next-pastry-poll?wpforms_return=demo-return-token": "frontend-poll-results",
    "pastry-poll-results": "frontend-poll-results--shortcode",
    "plan-your-catering": "frontend-lead-form",
    "profile": "klaviyo-example-profile",
    "recipe-swap": "frontend-form-locker--logged-in-member",
    "recipe-swap?snap_guest=1": "frontend-form-locker--logged-in-only",
    "reset-your-password": "frontend-user-reset",
    "reset-your-password?action=wpforms_rp&key=demo-reset-key&login=nobody": "frontend-user-reset--invalid",
    "reset-your-password?action=wpforms_rp&key=demo-reset-key&login=pip_reset": "frontend-user-reset--new-password",
    "save-your-order": "frontend-save-resume",
    "save-your-order?wpforms_sr_email_is_sent=2613": "frontend-save-resume--email-sent",
    "summer-baking-class": "frontend-form-locker--schedule-closed",
    "wholesale-price-list": "frontend-form-locker--password",
    "wp-admin": "wp-dashboard"
  },
  "v": {
    "admin.php?page=wpforms-analytics": [
      "form_id"
    ],
    "admin.php?page=wpforms-builder": [
      "form_id",
      "section",
      "snap_fx",
      "view"
    ],
    "admin.php?page=wpforms-entries": [
      "entry_id",
      "form_id",
      "status",
      "type",
      "view"
    ],
    "admin.php?page=wpforms-payments": [
      "mode",
      "payment_id",
      "status",
      "view"
    ],
    "admin.php?page=wpforms-settings": [
      "view"
    ],
    "admin.php?page=wpforms-tools": [
      "s",
      "status",
      "tab",
      "view"
    ],
    "customize.php": [
      "autofocus[section]"
    ],
    "index.php": [
      "entry",
      "p",
      "preview",
      "snap_pdf_output",
      "wpforms_form_preview",
      "wpforms_pdf_download"
    ],
    "know-your-bakes": [
      "snap_entry",
      "wpforms_return"
    ],
    "next-pastry-poll": [
      "wpforms_return"
    ],
    "recipe-swap": [
      "snap_guest"
    ],
    "reset-your-password": [
      "action",
      "key",
      "login"
    ],
    "save-your-order": [
      "wpforms_resume_entry",
      "wpforms_sr_email_is_sent"
    ]
  },
  "r": [
    {
      "page": "admin.php?page=wpforms-builder",
      "drop": [
        "snap"
      ]
    }
  ]
};
