/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for merchant.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 *   r  nav rules from products/merchant/nav-rules.json (applied to every key)
 * Rebuild after every capture batch: node tools/build-snap-nav.js merchant
 */
window.__snapNav = {
  "p": "merchant",
  "k": {
    "2": "frontend-product-video-shop",
    "1486": "frontend-account-view-order-1486",
    "1603": "frontend-account-view-order-1603",
    "1604": "frontend-account-view-order-1604",
    "1605": "frontend-account-view-order-1605",
    "1606": "frontend-account-view-order-1606",
    "1607": "frontend-account-view-order-1607",
    "1608": "frontend-account-view-order-1608",
    "1609": "frontend-advanced-reviews-account",
    "1621": "frontend-account-view-order-1621",
    "1636": "frontend-delivery-pickup-account",
    "1637": "frontend-account-view-order-1637",
    "1604?key=wc_order_v0qQxkj7J86GG": "frontend-frequently-bought-together-thankyou",
    "1606?key=wc_order_SArirGkt3b4Nz": "frontend-thankyou-offers-thankyou",
    "1607?key=wc_order_54xmmmAytfq8b": "frontend-checkout-thankyou",
    "1621?key=wc_order_7oxKI0luKV2OC": "frontend-product-bundles-thankyou",
    "about": "frontend-about",
    "admin.php?action=edit&id=1621&page=wc-orders": "admin-order-edit--bundle",
    "admin.php?action=edit&id=1636&page=wc-orders": "admin-order-edit--delivery-pickup",
    "admin.php?action=edit&id=1637&page=wc-orders": "admin-order-edit--pickup",
    "admin.php?action=edit&id=1652&page=wc-orders": "admin-order-edit--delivery-pickup-warning",
    "admin.php?campaign_id=fh-fg-3&module=free-gifts&page=merchant": "admin-module-free-gifts--coupon-offer",
    "admin.php?campaign_id=fh-po-2&module=pre-orders&page=merchant": "admin-module-pre-orders--rule-2-open",
    "admin.php?campaign_id=fh-ss-2&module=storewide-sale&page=merchant": "admin-module-storewide-sale--campaign-2-open",
    "admin.php?campaign_id=fh-vd-offer-2&module=volume-discounts&page=merchant": "admin-module-volume-discounts--offer-2-open",
    "admin.php?date=2026-09-01&page=merchant-delivery-calendar": "admin-delivery-calendar--prev-month",
    "admin.php?date=2026-11-01&page=merchant-delivery-calendar": "admin-delivery-calendar--next-month",
    "admin.php?fulfilment=pickup&page=merchant-delivery-calendar": "admin-delivery-calendar--filtered",
    "admin.php?merchant_dp_day=week&order=asc&orderby=merchant_delivery&page=wc-orders": "admin-orders--delivery-filter",
    "admin.php?module=add-to-cart-text&page=merchant": "admin-module-add-to-cart-text",
    "admin.php?module=added-to-cart-popup&page=merchant": "admin-module-added-to-cart-popup",
    "admin.php?module=added-to-cart-popup&page=merchant&snap=2": "admin-module-added-to-cart-popup--layout-2",
    "admin.php?module=added-to-cart-popup&page=merchant&snap=3": "admin-module-added-to-cart-popup--layout-3",
    "admin.php?module=address-autocomplete&page=merchant": "admin-module-address-autocomplete",
    "admin.php?module=advanced-reviews&page=merchant": "admin-module-advanced-reviews",
    "admin.php?module=advanced-reviews&page=merchant&snap=1": "admin-module-advanced-reviews--discount-on",
    "admin.php?module=advanced-reviews&page=merchant&snap=2": "admin-module-advanced-reviews--email-open",
    "admin.php?module=advanced-reviews&page=merchant&snap=3": "admin-module-advanced-reviews--carousel-open",
    "admin.php?module=advanced-reviews&page=merchant&snap=34": "admin-email-preview-review-request",
    "admin.php?module=advanced-reviews&page=merchant&snap=35": "admin-email-preview-review-discount",
    "admin.php?module=advanced-reviews&page=merchant&snap=4": "admin-module-advanced-reviews--reviews-picker-open",
    "admin.php?module=advanced-reviews&page=merchant&snap=43": "admin-email-preview-review-request-reminder",
    "admin.php?module=agree-to-terms-checkbox&page=merchant": "admin-module-agree-to-terms-checkbox",
    "admin.php?module=animated-add-to-cart&page=merchant": "admin-module-animated-add-to-cart",
    "admin.php?module=animated-add-to-cart&page=merchant&snap=glow": "admin-module-animated-add-to-cart--glow",
    "admin.php?module=auto-external-links&page=merchant": "admin-module-auto-external-links",
    "admin.php?module=buy-now&page=merchant": "admin-module-buy-now",
    "admin.php?module=buy-now&page=merchant&snap=campaign-open": "admin-module-buy-now--campaign-open",
    "admin.php?module=buy-now&page=merchant&snap=color-picker-open": "admin-module-buy-now--color-picker-open",
    "admin.php?module=buy-now&page=merchant&snap=products-picker-open": "admin-module-buy-now--products-picker-open",
    "admin.php?module=buy-x-get-y&page=merchant": "admin-module-buy-x-get-y",
    "admin.php?module=buy-x-get-y&page=merchant&snap=2": "admin-module-buy-x-get-y--offer-open",
    "admin.php?module=buy-x-get-y&page=merchant&snap=3": "admin-module-buy-x-get-y--free-shipping",
    "admin.php?module=buy-x-get-y&page=merchant&snap=pcart": "admin-module-buy-x-get-y--preview-cart",
    "admin.php?module=buy-x-get-y&page=merchant&snap=pcheckout": "admin-module-buy-x-get-y--preview-checkout",
    "admin.php?module=buy-x-get-y&page=merchant&snap=pthankyou": "admin-module-buy-x-get-y--preview-thankyou",
    "admin.php?module=cart-count-favicon&page=merchant": "admin-module-cart-count-favicon",
    "admin.php?module=cart-reserved-timer&page=merchant": "admin-module-cart-reserved-timer",
    "admin.php?module=checkout&page=merchant": "admin-module-checkout",
    "admin.php?module=clear-cart&page=merchant": "admin-module-clear-cart",
    "admin.php?module=clear-cart&page=merchant&snap=2": "admin-module-clear-cart--outline",
    "admin.php?module=clear-cart&page=merchant&snap=3": "admin-module-clear-cart--auto-clear",
    "admin.php?module=complementary-products&page=merchant": "admin-module-complementary-products",
    "admin.php?module=complementary-products&page=merchant&snap=2": "admin-module-complementary-products--offer-open",
    "admin.php?module=complementary-products&page=merchant&snap=3": "admin-module-complementary-products--layout-compact",
    "admin.php?module=complementary-products&page=merchant&snap=4": "admin-module-complementary-products--layout-carousel",
    "admin.php?module=complementary-products&page=merchant&snap=pcart": "admin-module-complementary-products--preview-cart",
    "admin.php?module=complementary-products&page=merchant&snap=pcheckout": "admin-module-complementary-products--preview-checkout",
    "admin.php?module=complementary-products&page=merchant&snap=pthankyou": "admin-module-complementary-products--preview-thankyou",
    "admin.php?module=cookie-banner&page=merchant": "admin-module-cookie-banner",
    "admin.php?module=countdown-timer&page=merchant": "admin-module-countdown-timer",
    "admin.php?module=countdown-timer&page=merchant&snap=color-open": "admin-module-countdown-timer--color-open",
    "admin.php?module=countdown-timer&page=merchant&snap=datepicker-open": "admin-module-countdown-timer--datepicker-open",
    "admin.php?module=countdown-timer&page=merchant&snap=evergreen": "admin-module-countdown-timer--evergreen",
    "admin.php?module=delivery-pickup&page=merchant": "admin-module-delivery-pickup",
    "admin.php?module=free-gifts&page=merchant": "admin-module-free-gifts",
    "admin.php?module=free-gifts&page=merchant&snap=3": "admin-module-free-gifts--add-offer-menu",
    "admin.php?module=free-shipping-progress-bar&page=merchant": "admin-module-free-shipping-progress-bar",
    "admin.php?module=frequently-bought-together&page=merchant": "admin-module-frequently-bought-together",
    "admin.php?module=frequently-bought-together&page=merchant&snap=2": "admin-module-frequently-bought-together--offer-open",
    "admin.php?module=frequently-bought-together&page=merchant&snap=3": "admin-module-frequently-bought-together--trigger-categories",
    "admin.php?module=frequently-bought-together&page=merchant&snap=4": "admin-module-frequently-bought-together--ai",
    "admin.php?module=frequently-bought-together&page=merchant&snap=5": "admin-module-frequently-bought-together--product-picker",
    "admin.php?module=frequently-bought-together&page=merchant&snap=pcart": "admin-module-frequently-bought-together--preview-cart",
    "admin.php?module=frequently-bought-together&page=merchant&snap=pcheckout": "admin-module-frequently-bought-together--preview-checkout",
    "admin.php?module=frequently-bought-together&page=merchant&snap=pthankyou": "admin-module-frequently-bought-together--preview-thankyou",
    "admin.php?module=inactive-tab-message&page=merchant": "admin-module-inactive-tab-message",
    "admin.php?module=login-popup&page=merchant": "admin-module-login-popup",
    "admin.php?module=login-popup&page=merchant&snap=register": "admin-module-login-popup--register",
    "admin.php?module=payment-logos&page=merchant": "admin-module-payment-logos",
    "admin.php?module=payment-logos&page=merchant&snap=color-picker-open": "admin-module-payment-logos--color-picker-open",
    "admin.php?module=payment-logos&page=merchant&snap=library": "admin-module-payment-logos--library",
    "admin.php?module=payment-logos&page=merchant&snap=media-open": "admin-module-payment-logos--media-open",
    "admin.php?module=pre-orders&page=merchant": "admin-module-pre-orders",
    "admin.php?module=pre-orders&page=merchant&snap=dp": "admin-module-pre-orders--date-picker-open",
    "admin.php?module=pre-orders&page=merchant&snap=mode": "admin-module-pre-orders--mode-only-pre-orders",
    "admin.php?module=product-audio&page=merchant": "admin-module-product-audio",
    "admin.php?module=product-brand-image&page=merchant": "admin-module-product-brand-image",
    "admin.php?module=product-bundles&page=merchant": "admin-module-product-bundles",
    "admin.php?module=product-labels&page=merchant": "admin-module-product-labels",
    "admin.php?module=product-labels&page=merchant&snap=color-picker-open": "admin-module-product-labels--color-picker-open",
    "admin.php?module=product-labels&page=merchant&snap=image-type": "admin-module-product-labels--image-type",
    "admin.php?module=product-labels&page=merchant&snap=label-open": "admin-module-product-labels--label-open",
    "admin.php?module=product-labels&page=merchant&snap=trigger-category": "admin-module-product-labels--trigger-category",
    "admin.php?module=product-navigation-links&page=merchant": "admin-module-product-navigation-links",
    "admin.php?module=product-swatches&page=merchant": "admin-module-product-swatches",
    "admin.php?module=product-video&page=merchant": "admin-module-product-video",
    "admin.php?module=quick-social-links&page=merchant": "admin-module-quick-social-links",
    "admin.php?module=quick-social-links&page=merchant&snap=add-menu-open": "admin-module-quick-social-links--add-menu-open",
    "admin.php?module=quick-social-links&page=merchant&snap=condition-open": "admin-module-quick-social-links--condition-open",
    "admin.php?module=quick-view&page=merchant": "admin-module-quick-view",
    "admin.php?module=quick-view&page=merchant&snap=2": "admin-module-quick-view--disable-menu",
    "admin.php?module=quick-view&page=merchant&snap=3": "admin-module-quick-view--feedback",
    "admin.php?module=quick-view&page=merchant&snap=4": "admin-module-quick-view--ai-prompts",
    "admin.php?module=quick-view&page=merchant&snap=color-picker-open": "admin-module-quick-view--color-picker-open",
    "admin.php?module=quick-view&page=merchant&snap=side-panel": "admin-module-quick-view--side-panel",
    "admin.php?module=quick-view&page=merchant&snap=suggested-on": "admin-module-quick-view--suggested-on",
    "admin.php?module=real-time-search&page=merchant": "admin-module-real-time-search",
    "admin.php?module=reasons-to-buy&page=merchant": "admin-module-reasons-to-buy",
    "admin.php?module=reasons-to-buy&page=merchant&snap=color-picker-open": "admin-module-reasons-to-buy--color-picker-open",
    "admin.php?module=reasons-to-buy&page=merchant&snap=icon-picker-open": "admin-module-reasons-to-buy--icon-picker-open",
    "admin.php?module=reasons-to-buy&page=merchant&snap=list-open": "admin-module-reasons-to-buy--list-open",
    "admin.php?module=recent-sales-notifications&page=merchant": "admin-module-recent-sales-notifications",
    "admin.php?module=recent-sales-notifications&page=merchant&snap=2": "admin-module-recent-sales-notifications--theme-template",
    "admin.php?module=recent-sales-notifications&page=merchant&snap=3": "admin-module-recent-sales-notifications--exclusion-on",
    "admin.php?module=recently-viewed-products&page=merchant": "admin-module-recently-viewed-products",
    "admin.php?module=recently-viewed-products&page=merchant&snap=color-picker-open": "admin-module-recently-viewed-products--color-picker-open",
    "admin.php?module=recently-viewed-products&page=merchant&snap=slider-on": "admin-module-recently-viewed-products--slider-on",
    "admin.php?module=scroll-to-top-button&page=merchant": "admin-module-scroll-to-top-button",
    "admin.php?module=scroll-to-top-button&page=merchant&snap=outline": "admin-module-scroll-to-top-button--outline",
    "admin.php?module=side-cart&page=merchant": "admin-module-side-cart",
    "admin.php?module=size-chart&page=merchant": "admin-module-size-chart",
    "admin.php?module=spending-goal&page=merchant": "admin-module-spending-goal",
    "admin.php?module=sticky-add-to-cart&page=merchant": "admin-module-sticky-add-to-cart",
    "admin.php?module=sticky-add-to-cart&page=merchant&snap=color-picker-open": "admin-module-sticky-add-to-cart--color-picker-open",
    "admin.php?module=sticky-add-to-cart&page=merchant&snap=exclusion-on": "admin-module-sticky-add-to-cart--exclusion-on",
    "admin.php?module=stock-scarcity&page=merchant": "admin-module-stock-scarcity",
    "admin.php?module=storewide-sale&page=merchant": "admin-module-storewide-sale",
    "admin.php?module=storewide-sale&page=merchant&snap=dates": "admin-module-storewide-sale--specific-dates",
    "admin.php?module=trust-badges&page=merchant": "admin-module-trust-badges",
    "admin.php?module=volume-discounts&page=merchant": "admin-module-volume-discounts",
    "admin.php?module=volume-discounts&page=merchant&snap=cat": "admin-module-volume-discounts--targeting-categories",
    "admin.php?module=volume-discounts&page=merchant&snap=pp": "admin-module-volume-discounts--product-picker-open",
    "admin.php?module=volume-discounts&page=merchant&snap=radio": "admin-module-volume-discounts--style-radio",
    "admin.php?module=wait-list&page=merchant": "admin-module-wait-list",
    "admin.php?module=wait-list&page=merchant&snap=41": "admin-email-preview-waitlist-stock-update",
    "admin.php?module=wait-list&page=merchant&snap=43": "admin-email-preview-waitlist-new-subscriber",
    "admin.php?module=wishlist&page=merchant": "admin-module-wishlist",
    "admin.php?module=wishlist&page=merchant&snap=categories-picker-open": "admin-module-wishlist--categories-picker-open",
    "admin.php?module=wishlist&page=merchant&snap=color-picker-open": "admin-module-wishlist--color-picker-open",
    "admin.php?module=wishlist&page=merchant&snap=sharing-link-open": "admin-module-wishlist--sharing-link-open",
    "admin.php?page=merchant": "admin-dashboard",
    "admin.php?page=merchant&section=analytics": "admin-analytics",
    "admin.php?page=merchant&section=analytics&snap=2": "admin-analytics--datepicker-open",
    "admin.php?page=merchant&section=campaigns": "admin-campaigns",
    "admin.php?page=merchant&section=campaigns&snap=2": "admin-campaigns--filtered",
    "admin.php?page=merchant&section=modules": "admin-modules",
    "admin.php?page=merchant&section=settings": "admin-settings",
    "admin.php?page=merchant&section=settings&snap=2": "admin-settings--save-bar",
    "admin.php?page=merchant&snap=2": "admin-dashboard--news-open",
    "admin.php?page=merchant-delivery-calendar": "admin-delivery-calendar",
    "admin.php?page=merchant-delivery-calendar&view=day": "admin-delivery-calendar-day",
    "admin.php?page=merchant-delivery-calendar&view=week": "admin-delivery-calendar-week",
    "admin.php?page=wc-admin": "admin-wc-home",
    "admin.php?page=wc-admin&path=/analytics/overview": "admin-wc-analytics",
    "admin.php?page=wc-admin&path=/customers": "admin-wc-customers",
    "admin.php?page=wc-admin&path=/marketing": "admin-wc-marketing",
    "admin.php?page=wc-orders": "admin-orders--delivery-column",
    "admin.php?page=wc-orders&status=all": "admin-orders--delivery-column",
    "admin.php?page=wc-orders&status=wc-pre-ordered": "admin-wc-orders--pre-ordered",
    "admin.php?page=wc-reports": "admin-wc-reports",
    "admin.php?page=wc-reports&report=sales_by_date&tab=orders": "admin-wc-reports",
    "admin.php?page=wc-reports&tab=orders": "admin-wc-reports",
    "admin.php?page=wc-settings": "admin-wc-settings",
    "admin.php?page=wc-settings&tab=general": "admin-wc-settings",
    "bedroom": "frontend-storewide-sale-shop",
    "billing": "frontend-account-edit-billing",
    "blog": "frontend-blog",
    "blue-channel-dining-chair": "frontend-volume-discounts-single",
    "blue-channel-dining-chair?orderby=photo-first": "frontend-advanced-reviews-single--sort-photo-first",
    "blue-channel-dining-chair?orderby=top-rated": "frontend-advanced-reviews-single--sort-top-rated",
    "blush-velvet-accent-chair": "frontend-stock-scarcity-single",
    "cart": "frontend-cart-checkout-offers-cart",
    "checkout": "frontend-checkout-checkout",
    "comment.php?action=editcomment&c=328": "admin-comment-edit-review-images",
    "contact": "frontend-contact",
    "cozy-lounge-armchair": "frontend-size-chart-single",
    "curved-lounge-chair": "frontend-buy-x-get-y-single",
    "decor": "frontend-buy-now-shop",
    "dining": "frontend-category-dining",
    "downloads": "frontend-account-downloads",
    "edit-account": "frontend-account-details",
    "edit-address": "frontend-account-addresses",
    "edit-comments.php": "admin-comments",
    "edit-comments.php?comment_status=all": "admin-comments",
    "edit-tags.php?post_type=product&taxonomy=pa_fabric-color": "admin-attribute-terms-color",
    "edit-tags.php?post_type=product&taxonomy=product_brand": "admin-product-brands",
    "edit-tags.php?post_type=product&taxonomy=product_cat": "admin-product-cats",
    "edit-tags.php?post_type=product&taxonomy=product_tag": "admin-product-tags",
    "edit-tags.php?taxonomy=category": "admin-post-categories",
    "edit.php": "admin-posts-list",
    "edit.php?page=product-reviews&post_type=product": "admin-comment-edit-review-images",
    "edit.php?page=product_attributes&post_type=product": "admin-product-attributes",
    "edit.php?post_status=wait_list_converted&post_type=waitlist_subscribers": "admin-waitlist-subscribers--purchased",
    "edit.php?post_status=wait_list_mailsent&post_type=waitlist_subscribers": "admin-waitlist-subscribers--mail-sent",
    "edit.php?post_status=wait_list_subscribed&post_type=waitlist_subscribers": "admin-waitlist-subscribers--subscribed",
    "edit.php?post_type=merchant_size_chart": "admin-size-charts",
    "edit.php?post_type=page": "admin-pages-list",
    "edit.php?post_type=post": "admin-posts-list",
    "edit.php?post_type=product": "admin-products-list",
    "edit.php?post_type=shop_coupon": "admin-coupons",
    "edit.php?post_type=waitlist_subscribers": "admin-waitlist-subscribers",
    "edit.php?post_type=waitlist_subscribers&subscribed_product=290": "admin-waitlist-subscribers--by-product",
    "home-office": "frontend-category-home-office",
    "living-room": "frontend-product-audio-shop",
    "my-account": "frontend-account-dashboard",
    "my-wishlist": "frontend-wishlist-page",
    "oak-nightstand": "frontend-storewide-sale-single",
    "open-shelf-bedside-table": "frontend-complementary-products-single",
    "options-general.php": "admin-settings-general",
    "orders": "frontend-account-orders",
    "outdoor": "frontend-category-outdoor",
    "packages": "frontend-category-packages",
    "plugins.php": "admin-plugins",
    "plugins.php?plugin_status=all": "admin-plugins",
    "post-new.php": "admin-post-new",
    "post-new.php?post_type=product": "admin-product-new--bundle-type",
    "post.php?action=edit&post=1619": "admin-product-edit-bundle",
    "post.php?action=edit&post=1619&snap=2": "admin-product-edit-bundle--item-settings",
    "post.php?action=edit&post=1619&snap=3": "admin-product-edit-bundle--search-results",
    "post.php?action=edit&post=1620": "admin-product-edit-bundle--per-product-discount",
    "post.php?action=edit&post=1634": "admin-size-chart-edit",
    "post.php?action=edit&post=219": "admin-product-edit-merchant-tab--product-video",
    "post.php?action=edit&post=231": "admin-product-edit-merchant-tab--add-to-cart-text",
    "post.php?action=edit&post=250": "admin-product-edit-merchant-tab--product-audio",
    "post.php?action=edit&post=255": "admin-product-edit-merchant-tab--product-brand-image",
    "post.php?action=edit&post=275": "admin-product-edit-merchant-tab--pre-orders",
    "reading-nook-set": "frontend-product-bundles-single",
    "shipping": "frontend-account-edit-shipping",
    "shop": "frontend-shop-all-modules",
    "swivel-lounge-chair": "frontend-pre-orders-single",
    "tall-open-shelf": "frontend-wait-list-single",
    "term.php?post_type=product&tag_ID=117&taxonomy=product_cat": "admin-product-cat-edit--size-chart",
    "term.php?post_type=product&tag_ID=118&taxonomy=pa_color": "admin-attribute-term-edit-color",
    "themes.php": "admin-themes",
    "upload.php": "admin-media-library",
    "upload.php?mode=grid": "admin-media-library",
    "users.php": "admin-users",
    "velvet-swivel-chair": "frontend-product-swatches-single",
    "white-stacking-chair": "frontend-buy-x-get-y-single--variable-gift"
  },
  "v": {
    "1604": [
      "key"
    ],
    "1606": [
      "key"
    ],
    "1607": [
      "key"
    ],
    "1621": [
      "key"
    ],
    "admin.php?page=merchant": [
      "campaign_id",
      "module",
      "section",
      "snap"
    ],
    "admin.php?page=merchant-delivery-calendar": [
      "date",
      "fulfilment",
      "view"
    ],
    "admin.php?page=wc-admin": [
      "path"
    ],
    "admin.php?page=wc-orders": [
      "action",
      "id",
      "merchant_dp_day",
      "order",
      "orderby",
      "status"
    ],
    "admin.php?page=wc-reports": [
      "report",
      "tab"
    ],
    "admin.php?page=wc-settings": [
      "tab"
    ],
    "blue-channel-dining-chair": [
      "orderby"
    ],
    "comment.php": [
      "action",
      "c"
    ],
    "edit-comments.php": [
      "comment_status"
    ],
    "edit-tags.php": [
      "post_type",
      "taxonomy"
    ],
    "edit.php": [
      "post_status",
      "post_type",
      "subscribed_product"
    ],
    "edit.php?page=product-reviews": [
      "post_type"
    ],
    "edit.php?page=product_attributes": [
      "post_type"
    ],
    "plugins.php": [
      "plugin_status"
    ],
    "post-new.php": [
      "post_type"
    ],
    "post.php": [
      "action",
      "post",
      "snap"
    ],
    "term.php": [
      "post_type",
      "tag_ID",
      "taxonomy"
    ],
    "upload.php": [
      "mode"
    ]
  },
  "r": [
    {
      "page": "1486",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1603",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1604",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1605",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1606",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1607",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1608",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1609",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1621",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1636",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "1637",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "2",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "about",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "bedroom",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "billing",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "blog",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "blue-channel-dining-chair",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "blush-velvet-accent-chair",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "cart",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "checkout",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "contact",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "cozy-lounge-armchair",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "curved-lounge-chair",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "decor",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "dining",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "downloads",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "edit-account",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "edit-address",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "home-office",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "index.php",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "living-room",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "my-account",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "my-wishlist",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "oak-nightstand",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "open-shelf-bedside-table",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "orders",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "outdoor",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "packages",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "reading-nook-set",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "shipping",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "shop",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "swivel-lounge-chair",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "tall-open-shelf",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "velvet-swivel-chair",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "white-stacking-chair",
      "drop": [
        "snap-cart",
        "snap_preset",
        "snap_modules_off",
        "snap_guest",
        "snap",
        "attribute_pa_body-finish",
        "attribute_pa_fabric-color",
        "merchant_waitlist_return"
      ]
    },
    {
      "page": "admin.php?page=merchant-delivery-calendar",
      "defaults": {
        "view": "month",
        "date": [
          "2026-10-02",
          "2026-10-05"
        ]
      }
    }
  ]
};
