/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for botiga.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 *   r  nav rules from products/botiga/nav-rules.json (applied to every key)
 * Rebuild after every capture batch: node tools/build-snap-nav.js botiga
 */
window.__snapNav = {
  "p": "botiga",
  "k": {
    "2": "frontend-shop--page-2",
    "1514": "frontend-my-account-view-order",
    "1514?key=wc_order_Od60YDbnLqFDg": "frontend-order-received",
    "about": "frontend-page-about",
    "admin.php?current_tab=ai-mcp&page=botiga-dashboard&tab=settings": "admin-botiga-dashboard-settings-ai-mcp",
    "admin.php?current_tab=general&page=botiga-dashboard&tab=settings": "admin-botiga-dashboard-settings-general",
    "admin.php?current_tab=misc&page=botiga-dashboard&tab=settings": "admin-botiga-dashboard-settings-misc",
    "admin.php?current_tab=performance&page=botiga-dashboard&tab=settings": "admin-botiga-dashboard-settings-performance",
    "admin.php?current_tab=white-label&page=botiga-dashboard&tab=settings": "admin-botiga-dashboard-settings-white-label",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=404": "admin-botiga-templates-builder-404",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=all-templates": "admin-botiga-templates-builder",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=cart": "admin-botiga-templates-builder-cart",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=checkout": "admin-botiga-templates-builder-checkout",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=content-block": "admin-botiga-templates-builder-content-block",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=create-new": "admin-botiga-templates-builder-create-new",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=my-account": "admin-botiga-templates-builder-my-account",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=order-received-page": "admin-botiga-templates-builder-order-received-page",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=post-archives": "admin-botiga-templates-builder-post-archives",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=product-archives": "admin-botiga-templates-builder-product-archives",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=single-page": "admin-botiga-templates-builder-single-page",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=single-post": "admin-botiga-templates-builder-single-post",
    "admin.php?module-page=builder&page=botiga-dashboard&settings-page=single-product": "admin-botiga-templates-builder-single-product",
    "admin.php?module-page=shop-filters&page=botiga-dashboard&settings-page=customization": "admin-botiga-product-filters-customization",
    "admin.php?module-page=shop-filters&page=botiga-dashboard&settings-page=filter-presets": "admin-botiga-product-filters",
    "admin.php?module-page=shop-filters&page=botiga-dashboard&settings-page=general": "admin-botiga-product-filters-general",
    "admin.php?module-page=shop-filters&page=botiga-dashboard&settings-page=seo": "admin-botiga-product-filters-seo",
    "admin.php?page=athemes-patcher-preview-bp": "admin-botiga-patcher",
    "admin.php?page=atss-onboarding-wizard": "wizard-getting-started",
    "admin.php?page=botiga-dashboard": "admin-botiga-dashboard",
    "admin.php?page=botiga-dashboard&tab=starter-sites": "admin-botiga-dashboard-starter-sites",
    "admin.php?page=wc-orders": "admin-orders-list",
    "admin.php?page=wc-orders&status=all": "admin-orders-list",
    "admin.php?page=wc-settings": "admin-wc-settings-general",
    "admin.php?page=wc-settings&section=&tab=advanced": "admin-wc-settings-advanced",
    "admin.php?page=wc-settings&section=&tab=products": "admin-wc-settings-products",
    "admin.php?page=wc-settings&section=&tab=shipping": "admin-wc-settings-shipping",
    "admin.php?page=wc-settings&section=options&tab=shipping": "admin-wc-settings-shipping-options",
    "admin.php?page=wc-settings&tab=account": "admin-wc-settings-account",
    "admin.php?page=wc-settings&tab=advanced": "admin-wc-settings-advanced",
    "admin.php?page=wc-settings&tab=checkout": "admin-wc-settings-checkout",
    "admin.php?page=wc-settings&tab=email": "admin-wc-settings-email",
    "admin.php?page=wc-settings&tab=general": "admin-wc-settings-general",
    "admin.php?page=wc-settings&tab=products": "admin-wc-settings-products",
    "admin.php?page=wc-settings&tab=shipping": "admin-wc-settings-shipping",
    "bedroom": "frontend-product-category--bedroom",
    "blog": "frontend-blog",
    "care-guides": "frontend-blog-category--care-guides",
    "careers?snap-cart=empty": "frontend-page-careers",
    "cart": "frontend-cart",
    "checkout": "frontend-checkout",
    "contact": "frontend-page-contact",
    "contact?snap-cart=empty": "frontend-page-contact",
    "cozy-lounge-armchair": "frontend-product-variable",
    "customize.php": "admin-customize",
    "customize.php?autofocus[panel]=botiga_panel_hooks": "admin-customize-panel-hooks",
    "customize.php?autofocus[panel]=botiga_panel_shop_archive": "admin-customize-panel-product-catalog",
    "customize.php?autofocus[panel]=botiga_panel_single_product": "admin-customize-panel-single-product",
    "customize.php?autofocus[panel]=botiga_panel_typography": "admin-customize-panel-typography",
    "customize.php?autofocus[panel]=nav_menus": "admin-customize-panel-menus",
    "customize.php?autofocus[panel]=widgets": "admin-customize-panel-widgets",
    "customize.php?autofocus[section]=add_menu": "admin-customize-add-menu",
    "customize.php?autofocus[section]=background_image": "admin-customize-background",
    "customize.php?autofocus[section]=botiga_breadcrumbs": "admin-customize-breadcrumbs",
    "customize.php?autofocus[section]=botiga_footer_row__main_footer_row_column1": "admin-customize-footer-column",
    "customize.php?autofocus[section]=botiga_google_autocomplete_section": "admin-customize-google-autocomplete",
    "customize.php?autofocus[section]=botiga_header_row__main_header_row_column1": "admin-customize-header-column",
    "customize.php?autofocus[section]=botiga_quicklinks": "admin-customize-quick-links",
    "customize.php?autofocus[section]=botiga_section_adtcnotif": "admin-customize-add-to-cart-notifications",
    "customize.php?autofocus[section]=botiga_section_blog_archives": "admin-customize-blog-archives",
    "customize.php?autofocus[section]=botiga_section_blog_singles": "admin-customize-blog-single",
    "customize.php?autofocus[section]=botiga_section_buttons": "admin-customize-buttons",
    "customize.php?autofocus[section]=botiga_section_buy_now": "admin-customize-buy-now",
    "customize.php?autofocus[section]=botiga_section_catalog_general": "admin-customize-woo-general",
    "customize.php?autofocus[section]=botiga_section_fb_above_footer_row": "admin-customize-footer-row-top",
    "customize.php?autofocus[section]=botiga_section_fb_below_footer_row": "admin-customize-footer-row-bottom",
    "customize.php?autofocus[section]=botiga_section_fb_component__button": "admin-customize-fb-button",
    "customize.php?autofocus[section]=botiga_section_fb_component__copyright": "admin-customize-fb-copyright",
    "customize.php?autofocus[section]=botiga_section_fb_component__footer_menu": "admin-customize-fb-footer-menu",
    "customize.php?autofocus[section]=botiga_section_fb_component__html": "admin-customize-fb-html",
    "customize.php?autofocus[section]=botiga_section_fb_component__shortcode": "admin-customize-fb-shortcode",
    "customize.php?autofocus[section]=botiga_section_fb_component__social": "admin-customize-fb-social",
    "customize.php?autofocus[section]=botiga_section_fb_component__widget1": "admin-customize-fb-widget1",
    "customize.php?autofocus[section]=botiga_section_fb_component__widget2": "admin-customize-fb-widget2",
    "customize.php?autofocus[section]=botiga_section_fb_main_footer_row": "admin-customize-footer-row-main",
    "customize.php?autofocus[section]=botiga_section_fb_wrapper": "admin-customize-footer-builder",
    "customize.php?autofocus[section]=botiga_section_footer_credits&snap_preset=legacy-hf": "admin-customize-legacy-footer-credits",
    "customize.php?autofocus[section]=botiga_section_footer_widgets&snap_preset=legacy-hf": "admin-customize-legacy-footer-widgets",
    "customize.php?autofocus[section]=botiga_section_free_shipping_progress_bar": "admin-customize-free-shipping-bar",
    "customize.php?autofocus[section]=botiga_section_hb_above_header_row": "admin-customize-header-row-top",
    "customize.php?autofocus[section]=botiga_section_hb_below_header_row": "admin-customize-header-row-bottom",
    "customize.php?autofocus[section]=botiga_section_hb_component__button": "admin-customize-hb-button",
    "customize.php?autofocus[section]=botiga_section_hb_component__button2": "admin-customize-hb-button2",
    "customize.php?autofocus[section]=botiga_section_hb_component__contact_info": "admin-customize-hb-contact-info",
    "customize.php?autofocus[section]=botiga_section_hb_component__html": "admin-customize-hb-html",
    "customize.php?autofocus[section]=botiga_section_hb_component__html2": "admin-customize-hb-html2",
    "customize.php?autofocus[section]=botiga_section_hb_component__login_register": "admin-customize-hb-login-register",
    "customize.php?autofocus[section]=botiga_section_hb_component__logo": "admin-customize-hb-logo",
    "customize.php?autofocus[section]=botiga_section_hb_component__menu": "admin-customize-hb-menu",
    "customize.php?autofocus[section]=botiga_section_hb_component__mobile_hamburger": "admin-customize-hb-mobile-hamburger",
    "customize.php?autofocus[section]=botiga_section_hb_component__mobile_offcanvas_menu": "admin-customize-hb-mobile-offcanvas-menu",
    "customize.php?autofocus[section]=botiga_section_hb_component__search": "admin-customize-hb-search",
    "customize.php?autofocus[section]=botiga_section_hb_component__secondary_menu": "admin-customize-hb-secondary-menu",
    "customize.php?autofocus[section]=botiga_section_hb_component__shortcode": "admin-customize-hb-shortcode",
    "customize.php?autofocus[section]=botiga_section_hb_component__social": "admin-customize-hb-social",
    "customize.php?autofocus[section]=botiga_section_hb_component__woo_icons": "admin-customize-hb-woo-icons",
    "customize.php?autofocus[section]=botiga_section_hb_main_header_row": "admin-customize-header-row-main",
    "customize.php?autofocus[section]=botiga_section_hb_mobile_offcanvas": "admin-customize-header-offcanvas",
    "customize.php?autofocus[section]=botiga_section_hb_presets": "admin-customize-header-layouts",
    "customize.php?autofocus[section]=botiga_section_hb_wrapper": "admin-customize-header-builder",
    "customize.php?autofocus[section]=botiga_section_header_icons&snap_preset=legacy-hf": "admin-customize-legacy-header-icons",
    "customize.php?autofocus[section]=botiga_section_hooks_content": "admin-customize-hooks-content",
    "customize.php?autofocus[section]=botiga_section_hooks_footer": "admin-customize-hooks-footer",
    "customize.php?autofocus[section]=botiga_section_hooks_general": "admin-customize-hooks-general",
    "customize.php?autofocus[section]=botiga_section_hooks_header": "admin-customize-hooks-header",
    "customize.php?autofocus[section]=botiga_section_hooks_sidebar": "admin-customize-hooks-sidebar",
    "customize.php?autofocus[section]=botiga_section_hooks_woocommerce": "admin-customize-hooks-woocommerce",
    "customize.php?autofocus[section]=botiga_section_hooks_woocommerce_general": "admin-customize-hooks-woo-general",
    "customize.php?autofocus[section]=botiga_section_hooks_woocommerce_shop_archive": "admin-customize-hooks-woo-shop-archive",
    "customize.php?autofocus[section]=botiga_section_hooks_woocommerce_shop_cart": "admin-customize-hooks-woo-cart",
    "customize.php?autofocus[section]=botiga_section_hooks_woocommerce_shop_checkout": "admin-customize-hooks-woo-checkout",
    "customize.php?autofocus[section]=botiga_section_hooks_woocommerce_shop_myaccount": "admin-customize-hooks-woo-myaccount",
    "customize.php?autofocus[section]=botiga_section_hooks_woocommerce_shop_single": "admin-customize-hooks-woo-single",
    "customize.php?autofocus[section]=botiga_section_layout": "admin-customize-layout",
    "customize.php?autofocus[section]=botiga_section_main_header&snap_preset=legacy-hf": "admin-customize-legacy-main-header",
    "customize.php?autofocus[section]=botiga_section_mobile_header&snap_preset=legacy-hf": "admin-customize-legacy-mobile-header",
    "customize.php?autofocus[section]=botiga_section_modal_popup": "admin-customize-modal-popup",
    "customize.php?autofocus[section]=botiga_section_product_swatches": "admin-customize-variation-swatches",
    "customize.php?autofocus[section]=botiga_section_product_swatches_swatch_button": "admin-customize-swatch-button",
    "customize.php?autofocus[section]=botiga_section_product_swatches_swatch_color": "admin-customize-swatch-color",
    "customize.php?autofocus[section]=botiga_section_product_swatches_swatch_image": "admin-customize-swatch-image",
    "customize.php?autofocus[section]=botiga_section_product_swatches_swatch_select": "admin-customize-swatch-select",
    "customize.php?autofocus[section]=botiga_section_scrolltotop": "admin-customize-scroll-to-top",
    "customize.php?autofocus[section]=botiga_section_shop_archive_categories": "admin-customize-catalog-categories",
    "customize.php?autofocus[section]=botiga_section_shop_archive_product_card": "admin-customize-catalog-product-card",
    "customize.php?autofocus[section]=botiga_section_shop_archive_sale_tag": "admin-customize-catalog-sale-tag",
    "customize.php?autofocus[section]=botiga_section_shop_cart": "admin-customize-cart",
    "customize.php?autofocus[section]=botiga_section_shop_search": "admin-customize-search",
    "customize.php?autofocus[section]=botiga_section_sidebar": "admin-customize-custom-sidebar",
    "customize.php?autofocus[section]=botiga_section_single_product_advanced_reviews": "admin-customize-advanced-reviews",
    "customize.php?autofocus[section]=botiga_section_single_product_layout": "admin-customize-single-layout",
    "customize.php?autofocus[section]=botiga_section_single_product_linked_variations": "admin-customize-linked-variations",
    "customize.php?autofocus[section]=botiga_section_single_product_size_chart": "admin-customize-size-chart",
    "customize.php?autofocus[section]=botiga_section_single_product_sticky_add_to_cart": "admin-customize-sticky-add-to-cart",
    "customize.php?autofocus[section]=botiga_section_single_product_tabs": "admin-customize-single-tabs",
    "customize.php?autofocus[section]=botiga_section_top_bar&snap_preset=legacy-hf": "admin-customize-legacy-top-bar",
    "customize.php?autofocus[section]=botiga_section_typography_body": "admin-customize-typography-body",
    "customize.php?autofocus[section]=botiga_section_typography_general": "admin-customize-typography-fonts",
    "customize.php?autofocus[section]=botiga_section_typography_header_menu": "admin-customize-typography-menu",
    "customize.php?autofocus[section]=botiga_section_typography_headings": "admin-customize-typography-headings",
    "customize.php?autofocus[section]=botiga_section_wishlist": "admin-customize-wishlist",
    "customize.php?autofocus[section]=colors": "admin-customize-colors",
    "customize.php?autofocus[section]=custom_css": "admin-customize-additional-css",
    "customize.php?autofocus[section]=header_image": "admin-customize-header-image",
    "customize.php?autofocus[section]=menu_locations": "admin-customize-menu-locations",
    "customize.php?autofocus[section]=nav_menu[131]": "admin-customize-menu-main",
    "customize.php?autofocus[section]=shop_single_recently_viewed_products_section&snap_preset=recently-viewed": "admin-customize-single-recently-viewed",
    "customize.php?autofocus[section]=shop_single_related_products_section": "admin-customize-single-related",
    "customize.php?autofocus[section]=shop_single_upsell_products_section": "admin-customize-single-upsell",
    "customize.php?autofocus[section]=side_mini_cart_floating_icon_section": "admin-customize-mini-cart-floating-icon",
    "customize.php?autofocus[section]=sidebar-widgets-footer-1": "admin-customize-widgets-footer-1",
    "customize.php?autofocus[section]=sidebar-widgets-footer-2": "admin-customize-widgets-footer-2",
    "customize.php?autofocus[section]=sidebar-widgets-footer-3": "admin-customize-widgets-footer-3",
    "customize.php?autofocus[section]=sidebar-widgets-footer-4": "admin-customize-widgets-footer-4",
    "customize.php?autofocus[section]=sidebar-widgets-shop-sidebar-1": "admin-customize-widgets-shop-sidebar",
    "customize.php?autofocus[section]=sidebar-widgets-shop-sidebar-1&snap_preset=shop-sidebar-left": "admin-customize-widgets-shop-sidebar",
    "customize.php?autofocus[section]=sidebar-widgets-sidebar-1": "admin-customize-widgets-sidebar",
    "customize.php?autofocus[section]=sidebar-widgets-sidebar-1&snap_preset=blog-sidebar-right": "admin-customize-widgets-sidebar",
    "customize.php?autofocus[section]=static_front_page": "admin-customize-homepage-settings",
    "customize.php?autofocus[section]=title_tagline": "admin-customize-site-identity",
    "customize.php?autofocus[section]=woocommerce_checkout": "admin-customize-checkout",
    "customize.php?autofocus[section]=woocommerce_product_catalog": "admin-customize-catalog-layout",
    "customize.php?autofocus[section]=woocommerce_product_images": "admin-customize-product-images",
    "customize.php?autofocus[section]=woocommerce_store_notice": "admin-customize-store-notice",
    "design-tips": "frontend-blog-category--design-tips",
    "dining": "frontend-product-category--dining",
    "edit-account": "frontend-my-account-edit-account",
    "edit-address": "frontend-my-account-edit-address",
    "edit-comments.php": "admin-comments",
    "edit-comments.php?comment_status=all": "admin-comments",
    "edit-tags.php?post_type=product&taxonomy=product_cat": "admin-edit-tags-product-cat",
    "edit.php": "admin-posts-list",
    "edit.php?page=product_attributes&post_type=product": "admin-product-attributes",
    "edit.php?post_type=linked_variation": "admin-edit-linked-variation",
    "edit.php?post_type=page": "admin-pages-list",
    "edit.php?post_type=post": "admin-posts-list",
    "edit.php?post_type=product": "admin-products-list",
    "edit.php?post_type=size_chart": "admin-edit-size-chart",
    "faqs?snap-cart=empty": "frontend-page-faqs",
    "home-office": "frontend-product-category--home-office",
    "how-it-works?snap-cart=empty": "frontend-page-how-it-works",
    "how-to-choose-a-sofa-that-fits-your-room-and-your-life": "frontend-blog-single",
    "index.php?post_type=product&s=chair": "frontend-search",
    "index.php?post_type=product&s=zzzz": "frontend-search--no-results",
    "inside-fernhill": "frontend-blog-category--inside-fernhill",
    "living-room": "frontend-product-category",
    "media-new.php": "admin-media-new",
    "my-account": "frontend-my-account",
    "my-wishlist": "frontend-wishlist",
    "nav-menus.php": "admin-nav-menus",
    "nav-menus.php?action=locations": "admin-nav-menus--locations",
    "no-such-page-fernhill": "frontend-404",
    "options-general.php": "admin-settings-general",
    "orders": "frontend-my-account-orders",
    "outdoor": "frontend-product-category--outdoor",
    "packages": "frontend-product-category--packages",
    "plugins.php": "admin-plugins",
    "plugins.php?plugin_status=all": "admin-plugins",
    "post-new.php": "admin-post-new",
    "post.php?action=edit&post=1407": "admin-post-page",
    "post.php?action=edit&post=1625": "admin-post-size-chart",
    "post.php?action=edit&post=1648": "admin-post-athemes-hf",
    "post.php?action=edit&post=1656": "admin-post-linked-variation",
    "post.php?action=edit&post=219": "admin-post-product--inventory",
    "post.php?action=edit&post=231": "admin-post-product",
    "post.php?action=edit&post=329": "admin-post-post",
    "privacy-policy?snap-cart=empty": "frontend-page-privacy-policy",
    "profile.php": "admin-profile",
    "refund_returns?snap-cart=empty": "frontend-page-refund-returns",
    "reviews?snap-cart=empty": "frontend-page-reviews",
    "shop": "frontend-shop",
    "shop?filter_body-finish=grey": "frontend-shop--filtered",
    "shop?orderby=price": "frontend-shop--sorted",
    "swivel-lounge-chair": "frontend-product-video",
    "term.php?post_type=product&tag_ID=123&taxonomy=pa_body-finish": "admin-term-pa-color",
    "term.php?post_type=product&tag_ID=125&taxonomy=product_cat": "admin-edit-tags-product-cat",
    "terms?snap-cart=empty": "frontend-page-terms",
    "themes.php": "admin-themes--botiga-hero",
    "upload.php": "admin-media-library",
    "upload.php?mode=grid": "admin-media-library",
    "upload.php?mode=list": "admin-media-library--list",
    "user-new.php": "admin-user-new",
    "users.php": "admin-users",
    "velvet-swivel-chair": "frontend-product-simple",
    "velvet-swivel-chair?botiga-adtc-added-to-cart=219&variation_id=225": "frontend-product-simple--atc-toast",
    "velvet-swivel-chair?orderby=top-rated": "frontend-product-simple--reviews-top-rated",
    "welcome": "frontend-home--modal-popup",
    "widgets.php": "admin-widgets--shop-sidebar"
  },
  "v": {
    "1514": [
      "key"
    ],
    "admin.php?page=botiga-dashboard": [
      "current_tab",
      "module-page",
      "settings-page",
      "tab"
    ],
    "admin.php?page=wc-orders": [
      "status"
    ],
    "admin.php?page=wc-settings": [
      "section",
      "tab"
    ],
    "careers": [
      "snap-cart"
    ],
    "contact": [
      "snap-cart"
    ],
    "customize.php": [
      "autofocus[panel]",
      "autofocus[section]",
      "snap_preset"
    ],
    "edit-comments.php": [
      "comment_status"
    ],
    "edit-tags.php": [
      "post_type",
      "taxonomy"
    ],
    "edit.php": [
      "post_type"
    ],
    "edit.php?page=product_attributes": [
      "post_type"
    ],
    "faqs": [
      "snap-cart"
    ],
    "how-it-works": [
      "snap-cart"
    ],
    "index.php": [
      "post_type",
      "s"
    ],
    "nav-menus.php": [
      "action"
    ],
    "plugins.php": [
      "plugin_status"
    ],
    "post.php": [
      "action",
      "post"
    ],
    "privacy-policy": [
      "snap-cart"
    ],
    "refund_returns": [
      "snap-cart"
    ],
    "reviews": [
      "snap-cart"
    ],
    "shop": [
      "filter_body-finish",
      "orderby"
    ],
    "term.php": [
      "post_type",
      "tag_ID",
      "taxonomy"
    ],
    "terms": [
      "snap-cart"
    ],
    "upload.php": [
      "mode"
    ],
    "velvet-swivel-chair": [
      "botiga-adtc-added-to-cart",
      "orderby",
      "variation_id"
    ]
  },
  "r": [
    {
      "page": "1514",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "2",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "about",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "admin.php?page=athemes-patcher-preview-bp",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "admin.php?page=atss-onboarding-wizard",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "admin.php?page=botiga-dashboard",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "admin.php?page=wc-orders",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "admin.php?page=wc-settings",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "bedroom",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "blog",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "care-guides",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "cart",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "checkout",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "cozy-lounge-armchair",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "customize.php",
      "drop": [
        "url"
      ]
    },
    {
      "page": "design-tips",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "dining",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "edit-account",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "edit-address",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "edit-comments.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "edit.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "edit.php?page=product_attributes",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "home-office",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "how-to-choose-a-sofa-that-fits-your-room-and-your-life",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "index.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "inside-fernhill",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "living-room",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "my-account",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "my-wishlist",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "nav-menus.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "no-such-page-fernhill",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "options-general.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "orders",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "outdoor",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "packages",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "plugins.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "post.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "profile.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "shop",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "swivel-lounge-chair",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "term.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "themes.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "upload.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "users.php",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "velvet-swivel-chair",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    },
    {
      "page": "welcome",
      "drop": [
        "snap-cart",
        "snap-user",
        "snap-wishlist",
        "snap_preset"
      ]
    }
  ]
};
