/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for duplicator.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 *   r  nav rules from products/duplicator/nav-rules.json (applied to every key)
 * Rebuild after every capture batch: node tools/build-snap-nav.js duplicator
 */
window.__snapNav = {
  "p": "duplicator",
  "k": {
    "admin.php?dup-save-message=Storage Updated.&inner_page=edit&page=duplicator-storage&storage_id=15": "admin-storage-edit--saved-message",
    "admin.php?filter_date_from=2026-09-25&filter_date_to=2026-09-28&page=duplicator-activity-log": "admin-activity-log--date-range",
    "admin.php?filter_search=danasdarkroom_db&page=duplicator-activity-log": "admin-activity-log--search",
    "admin.php?filter_search=invoice&page=duplicator-activity-log": "admin-activity-log--search-no-results",
    "admin.php?filter_severity=30&page=duplicator-activity-log": "admin-activity-log--severity-error",
    "admin.php?filter_show_all=1&page=duplicator-activity-log": "admin-activity-log--show-all",
    "admin.php?filter_show_all=1&page=duplicator-activity-log&paged=2": "admin-activity-log--show-all-page-2",
    "admin.php?filter_type=backup_create&page=duplicator-activity-log": "admin-activity-log--type-backup-create",
    "admin.php?id=0&inner_page=edit&page=duplicator-settings&tab=brand": "admin-settings-brand-edit--default",
    "admin.php?id=12&inner_page=detail&page=duplicator": "admin-backups-detail-db-0929",
    "admin.php?id=12&inner_page=transfer&page=duplicator": "admin-backups-transfer-db-0929",
    "admin.php?id=13&inner_page=detail&page=duplicator": "admin-backups-detail-lightweight-0929",
    "admin.php?id=13&inner_page=transfer&page=duplicator": "admin-backups-transfer-lightweight-0929",
    "admin.php?id=14&inner_page=detail&page=duplicator": "admin-backups-detail-db-0930",
    "admin.php?id=14&inner_page=transfer&page=duplicator": "admin-backups-transfer-db-0930",
    "admin.php?id=15&inner_page=detail&page=duplicator": "admin-backups-detail-lightweight-0930",
    "admin.php?id=15&inner_page=transfer&page=duplicator": "admin-backups-transfer-lightweight-0930",
    "admin.php?id=2&inner_page=detail&page=duplicator": "admin-backups-detail-full-site",
    "admin.php?id=2&inner_page=transfer&page=duplicator": "admin-backups-transfer-full-site",
    "admin.php?id=3&inner_page=detail&page=duplicator": "admin-backups-detail-lightweight",
    "admin.php?id=3&inner_page=transfer&page=duplicator": "admin-backups-transfer-lightweight-0920",
    "admin.php?id=41&inner_page=edit&page=duplicator-settings&tab=brand": "admin-settings-brand-edit-darkroom",
    "admin.php?id=42&inner_page=edit&page=duplicator-settings&tab=brand": "admin-settings-brand-edit-client-handoff",
    "admin.php?id=5&inner_page=detail&page=duplicator": "admin-backups-detail-db-0921",
    "admin.php?id=5&inner_page=transfer&page=duplicator": "admin-backups-transfer-db-0921",
    "admin.php?id=6&inner_page=detail&page=duplicator": "admin-backups-detail-lightweight-0923",
    "admin.php?id=6&inner_page=transfer&page=duplicator": "admin-backups-transfer-lightweight-0923",
    "admin.php?id=7&inner_page=detail&page=duplicator": "admin-backups-detail-db-only",
    "admin.php?id=7&inner_page=transfer&page=duplicator": "admin-backups-transfer-db-only",
    "admin.php?id=8&inner_page=detail&page=duplicator": "admin-backups-detail-lightweight-0926",
    "admin.php?id=8&inner_page=transfer&page=duplicator": "admin-backups-transfer-lightweight",
    "admin.php?id=9&inner_page=detail&page=duplicator": "admin-backups-detail-db-notes",
    "admin.php?id=9&inner_page=transfer&page=duplicator": "admin-backups-transfer-db-notes",
    "admin.php?id=999999&inner_page=detail&page=duplicator": "admin-backups-detail--not-found",
    "admin.php?inner_page=edit&package_template_id=32&page=duplicator-tools&tab=templates": "admin-tools-templates-edit-lightweight",
    "admin.php?inner_page=edit&package_template_id=33&page=duplicator-tools&tab=templates": "admin-tools-templates-edit-db-only",
    "admin.php?inner_page=edit&package_template_id=34&page=duplicator-tools&tab=templates": "admin-tools-templates-edit-media",
    "admin.php?inner_page=edit&package_template_id=35&page=duplicator-tools&tab=templates": "admin-tools-templates-edit-code",
    "admin.php?inner_page=edit&package_template_id=6&page=duplicator-tools&tab=templates": "admin-tools-templates-edit-default",
    "admin.php?inner_page=edit&page=duplicator-schedules": "admin-schedules-edit--new",
    "admin.php?inner_page=edit&page=duplicator-schedules&schedule_id=36": "admin-schedules-edit-daily",
    "admin.php?inner_page=edit&page=duplicator-schedules&schedule_id=37": "admin-schedules-edit-weekly",
    "admin.php?inner_page=edit&page=duplicator-schedules&schedule_id=38": "admin-schedules-edit-monthly",
    "admin.php?inner_page=edit&page=duplicator-schedules&schedule_id=39": "admin-schedules-edit-hourly",
    "admin.php?inner_page=edit&page=duplicator-settings&tab=brand": "admin-settings-brand-edit--new",
    "admin.php?inner_page=edit&page=duplicator-storage": "admin-storage-new",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=15": "admin-storage-edit-amazon-s3",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=16": "admin-storage-edit-s3-compatible",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=17": "admin-storage-edit-backblaze-b2",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=18": "admin-storage-edit-wasabi",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=19": "admin-storage-edit-cloudflare-r2",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=20": "admin-storage-edit-vultr",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=21": "admin-storage-edit-dream-objects",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=22": "admin-storage-edit-digitalocean-spaces",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=23": "admin-storage-edit-google-cloud-storage",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=24": "admin-storage-edit-ftp",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=25": "admin-storage-edit-google-drive",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=26": "admin-storage-edit-dropbox",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=27": "admin-storage-edit-onedrive",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=3": "admin-storage-edit-default",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=40": "admin-storage-edit-local",
    "admin.php?inner_page=edit&page=duplicator-storage&storage_id=5": "admin-storage-edit-duplicator-cloud",
    "admin.php?inner_page=edit&page=duplicator-tools&tab=templates": "admin-tools-templates-edit--new",
    "admin.php?inner_page=new1&page=duplicator": "admin-backups-new-setup",
    "admin.php?inner_page=new2&page=duplicator": "admin-backups-new-scan",
    "admin.php?open_log_id=11&page=duplicator-activity-log": "admin-activity-log--detail-lightweight",
    "admin.php?open_log_id=18&page=duplicator-activity-log": "admin-activity-log--detail-failed-backup",
    "admin.php?open_log_id=23&page=duplicator-activity-log": "admin-activity-log--detail-db-0921",
    "admin.php?open_log_id=30&page=duplicator-activity-log": "admin-activity-log--detail-lightweight-0923",
    "admin.php?open_log_id=37&page=duplicator-activity-log": "admin-activity-log--detail-db-only",
    "admin.php?open_log_id=4&page=duplicator-activity-log": "admin-activity-log--detail-full-site",
    "admin.php?open_log_id=44&page=duplicator-activity-log": "admin-activity-log--detail-lightweight-0926",
    "admin.php?open_log_id=51&page=duplicator-activity-log": "admin-activity-log--detail-db-notes",
    "admin.php?open_log_id=62&page=duplicator-activity-log": "admin-activity-log--detail-db-0929",
    "admin.php?open_log_id=69&page=duplicator-activity-log": "admin-activity-log--detail-lightweight-0929",
    "admin.php?open_log_id=76&page=duplicator-activity-log": "admin-activity-log--detail-db-0930",
    "admin.php?open_log_id=83&page=duplicator-activity-log": "admin-activity-log--detail-lightweight-0930",
    "admin.php?open_log_id=9&page=duplicator-activity-log": "admin-activity-log--detail-scan",
    "admin.php?page=duplicator": "admin-backups",
    "admin.php?page=duplicator&paged=2": "admin-backups--page-2",
    "admin.php?page=duplicator-activity-log": "admin-activity-log",
    "admin.php?page=duplicator-dynamic-help&tag=": "admin-help",
    "admin.php?page=duplicator-dynamic-help&tag=backup_step_1": "admin-help-backup-step-1",
    "admin.php?page=duplicator-dynamic-help&tag=backup_step_2": "admin-help",
    "admin.php?page=duplicator-dynamic-help&tag=backups": "admin-help-backups",
    "admin.php?page=duplicator-dynamic-help&tag=import": "admin-help-import",
    "admin.php?page=duplicator-dynamic-help&tag=recovery": "admin-help-recovery",
    "admin.php?page=duplicator-dynamic-help&tag=schedule_edit": "admin-help-schedule-edit",
    "admin.php?page=duplicator-dynamic-help&tag=schedules": "admin-help-schedules",
    "admin.php?page=duplicator-dynamic-help&tag=settings": "admin-help",
    "admin.php?page=duplicator-dynamic-help&tag=storage_edit": "admin-help",
    "admin.php?page=duplicator-dynamic-help&tag=storages": "admin-help",
    "admin.php?page=duplicator-dynamic-help&tag=template_edit": "admin-help-template-edit",
    "admin.php?page=duplicator-dynamic-help&tag=templates": "admin-help-templates",
    "admin.php?page=duplicator-dynamic-help&tag=tools": "admin-help",
    "admin.php?page=duplicator-email-summary-preview": "admin-email-summary-preview",
    "admin.php?page=duplicator-import": "admin-import",
    "admin.php?page=duplicator-schedules": "admin-schedules",
    "admin.php?page=duplicator-settings": "admin-settings-general",
    "admin.php?page=duplicator-settings&tab=brand": "admin-settings-brand",
    "admin.php?page=duplicator-settings&tab=capabilities": "admin-settings-capabilities",
    "admin.php?page=duplicator-settings&tab=general": "admin-settings-general",
    "admin.php?page=duplicator-settings&tab=import": "admin-settings-import",
    "admin.php?page=duplicator-settings&tab=migrate": "admin-settings-migrate",
    "admin.php?page=duplicator-settings&tab=package": "admin-settings-package",
    "admin.php?page=duplicator-settings&tab=schedule": "admin-settings-schedule",
    "admin.php?page=duplicator-settings&tab=storage": "admin-settings-storage",
    "admin.php?page=duplicator-staging": "admin-staging",
    "admin.php?page=duplicator-storage": "admin-storage",
    "admin.php?page=duplicator-tools": "admin-tools-general",
    "admin.php?page=duplicator-tools&tab=ai": "admin-tools-ai",
    "admin.php?page=duplicator-tools&tab=auto-tune": "admin-tools-auto-tune",
    "admin.php?page=duplicator-tools&tab=general": "admin-tools-general",
    "admin.php?page=duplicator-tools&tab=logs": "admin-tools-logs",
    "admin.php?page=duplicator-tools&tab=php-logs": "admin-tools-php-logs",
    "admin.php?page=duplicator-tools&tab=recovery": "admin-tools-recovery",
    "admin.php?page=duplicator-tools&tab=server-info": "admin-tools-server-info",
    "admin.php?page=duplicator-tools&tab=templates": "admin-tools-templates",
    "index.php": "admin-dashboard--widget"
  },
  "v": {
    "admin.php?page=duplicator": [
      "id",
      "inner_page",
      "paged"
    ],
    "admin.php?page=duplicator-activity-log": [
      "filter_date_from",
      "filter_date_to",
      "filter_search",
      "filter_severity",
      "filter_show_all",
      "filter_type",
      "open_log_id",
      "paged"
    ],
    "admin.php?page=duplicator-dynamic-help": [
      "tag"
    ],
    "admin.php?page=duplicator-schedules": [
      "inner_page",
      "schedule_id"
    ],
    "admin.php?page=duplicator-settings": [
      "id",
      "inner_page",
      "tab"
    ],
    "admin.php?page=duplicator-storage": [
      "dup-save-message",
      "inner_page",
      "storage_id"
    ],
    "admin.php?page=duplicator-tools": [
      "inner_page",
      "package_template_id",
      "tab"
    ]
  },
  "r": [
    {
      "page": "admin.php?page=duplicator-activity-log",
      "drop": [
        "filter_action"
      ],
      "defaults": {
        "filter_show_all": [
          "",
          "0"
        ],
        "filter_date_from": "",
        "filter_date_to": "",
        "filter_severity": "-1",
        "filter_type": "",
        "filter_search": "",
        "paged": "1"
      }
    },
    {
      "page": "admin.php?page=duplicator",
      "when": {
        "paged": "1"
      },
      "drop": [
        "paged"
      ]
    },
    {
      "page": "admin.php?page=duplicator-settings",
      "when": {
        "tab": "brand",
        "inner_page": "edit"
      },
      "drop": [
        "action"
      ],
      "defaults": {
        "id": "-1"
      }
    }
  ]
};
