/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for athemes-addons.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 * Rebuild after every capture batch: node tools/build-snap-nav.js athemes-addons
 */
window.__snapNav = {
  "p": "athemes-addons",
  "k": {
    "admin.php?page=at-blocks": "admin-blocks",
    "admin.php?page=at-blocks&path=blocks": "admin-blocks",
    "admin.php?page=at-blocks&path=settings&section=editor-options": "admin-blocks-settings-editor-options",
    "admin.php?page=at-blocks&path=settings&section=performance": "admin-blocks-settings-performance",
    "admin.php?page=athemes-addons": "admin-addons-widgets",
    "admin.php?page=athemes-addons&section=extensions": "admin-addons-extensions",
    "admin.php?page=athemes-addons&section=settings": "admin-addons-settings--license-active",
    "admin.php?page=athemes-addons&section=theme-builder": "admin-addons-theme-builder--populated",
    "admin.php?page=athemes-addons&section=widgets": "admin-addons-widgets",
    "admin.php?page=elementor": "admin-elementor-templates",
    "admin.php?page=elementor-home": "admin-elementor-home",
    "case-studies": "frontend-tb-archive",
    "clients-reviews": "frontend-clients-reviews",
    "contact-northline": "frontend-contact-northline",
    "edit-comments.php": "admin-comments",
    "edit-comments.php?comment_status=all": "admin-comments",
    "edit.php": "admin-posts-list",
    "edit.php?all_posts=1&post_type=post": "admin-posts-list",
    "edit.php?post_type=aafe_templates": "admin-templates-list",
    "edit.php?post_type=elementor_library": "admin-elementor-templates",
    "edit.php?post_type=elementor_library&tabs_group=library": "admin-elementor-templates",
    "edit.php?post_type=page": "admin-pages-list",
    "how-we-work": "frontend-how-we-work",
    "index.php": "admin-dashboard",
    "journal-blocks": "frontend-journal-blocks",
    "options-general.php": "admin-settings-general",
    "our-team": "frontend-our-team",
    "people-and-proof": "frontend-people-and-proof",
    "plugins.php": "admin-plugins",
    "plugins.php?plugin_status=all": "admin-plugins",
    "post-new.php": "admin-post-new",
    "post.php?action=edit&post=1849": "editor-block-heading",
    "post.php?action=edit&post=1850": "editor-block-team",
    "post.php?action=edit&post=1851": "editor-block-post-grid",
    "post.php?action=edit&post=1852": "editor-block-google-maps",
    "selected-work": "frontend-selected-work",
    "services-pricing": "frontend-services-pricing",
    "studio-basics": "frontend-studio-basics",
    "studio-extras": "frontend-studio-extras",
    "studio-films": "frontend-studio-films",
    "studio-in-numbers": "frontend-studio-in-numbers",
    "studio-journal": "frontend-studio-journal",
    "studio-resources": "frontend-studio-resources",
    "theme-builder-preview": "frontend-theme-builder-preview",
    "themes.php": "admin-themes",
    "this-page-does-not-exist": "frontend-tb-404",
    "update-core.php": "admin-updates",
    "upload.php": "admin-media-library",
    "upload.php?mode=grid": "admin-media-library",
    "upload.php?mode=list": "admin-media-library--list",
    "user-new.php": "admin-user-new",
    "users.php": "admin-users",
    "what-a-good-brand-guide-actually-contains": "frontend-tb-single",
    "work-with-us": "frontend-work-with-us"
  },
  "v": {
    "admin.php?page=at-blocks": [
      "path",
      "section"
    ],
    "admin.php?page=athemes-addons": [
      "section"
    ],
    "edit-comments.php": [
      "comment_status"
    ],
    "edit.php": [
      "all_posts",
      "post_type",
      "tabs_group"
    ],
    "plugins.php": [
      "plugin_status"
    ],
    "post.php": [
      "action",
      "post"
    ],
    "upload.php": [
      "mode"
    ]
  }
};
