/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for optinmonster.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 * Rebuild after every capture batch: node tools/build-snap-nav.js optinmonster
 */
window.__snapNav = {
  "p": "optinmonster",
  "k": {
    "admin.php?campaignId=rurs58pqxwh1hlveqtqr&page=optin-monster-campaigns": "admin-campaigns-output-inline",
    "admin.php?campaignId=tjrnkuhbdzfebjblahxo&page=optin-monster-campaigns": "admin-campaigns-output",
    "admin.php?campaignId=tjrnkuhbdzfebjblahxo&page=optin-monster-monsterleads&selectedTab=contacts": "admin-monsterleads-contacts--campaign-filtered",
    "admin.php?page=optin-monster-about": "admin-about-about-us",
    "admin.php?page=optin-monster-about&selectedTab=getting-started": "admin-about-getting-started",
    "admin.php?page=optin-monster-campaigns": "admin-campaigns",
    "admin.php?page=optin-monster-campaigns&searchTerm=Pantry": "admin-campaigns--search-results",
    "admin.php?page=optin-monster-dashboard": "admin-dashboard",
    "admin.php?page=optin-monster-monsterleads": "admin-monsterleads-contacts",
    "admin.php?page=optin-monster-monsterleads&selectedTab=contacts": "admin-monsterleads-contacts",
    "admin.php?page=optin-monster-personalization": "admin-personalization",
    "admin.php?page=optin-monster-playbooks": "admin-playbooks",
    "admin.php?page=optin-monster-seedprod": "admin-seedprod",
    "admin.php?page=optin-monster-settings": "admin-settings-general",
    "admin.php?page=optin-monster-settings&selectedTab=misc": "admin-settings-misc",
    "admin.php?page=optin-monster-settings&selectedTab=site": "admin-settings-site",
    "admin.php?page=optin-monster-templates": "admin-templates",
    "admin.php?page=optin-monster-templates&type=floating": "admin-templates-floating",
    "admin.php?page=optin-monster-templates&type=fullscreen": "admin-templates-fullscreen",
    "admin.php?page=optin-monster-templates&type=gamified": "admin-templates-gamified",
    "admin.php?page=optin-monster-templates&type=inline": "admin-templates-inline",
    "admin.php?page=optin-monster-templates&type=slide": "admin-templates-slide",
    "admin.php?page=optin-monster-trustpulse": "admin-trustpulse",
    "admin.php?page=optin-monster-university": "admin-university",
    "homemade-granola-recipe-our-pantry-favorite": "frontend-inline-shortcode",
    "index.php": "frontend-popup",
    "plugins.php": "admin-plugins-row",
    "plugins.php?plugin_status=all": "admin-plugins-row"
  },
  "v": {
    "admin.php?page=optin-monster-about": [
      "selectedTab"
    ],
    "admin.php?page=optin-monster-campaigns": [
      "campaignId",
      "searchTerm"
    ],
    "admin.php?page=optin-monster-monsterleads": [
      "campaignId",
      "selectedTab"
    ],
    "admin.php?page=optin-monster-settings": [
      "selectedTab"
    ],
    "admin.php?page=optin-monster-templates": [
      "type"
    ],
    "plugins.php": [
      "plugin_status"
    ]
  }
};
