/* GENERATED by tools/build-snap-nav.js — do not edit.
 * Snapshot navigation map for aioseo.
 *   k  canonical link key -> snapshot slug
 *   v  page id -> the params this screen's siblings vary on
 *   r  nav rules from products/aioseo/nav-rules.json (applied to every key)
 * Rebuild after every capture batch: node tools/build-snap-nav.js aioseo
 */
window.__snapNav = {
  "p": "aioseo",
  "k": {
    "about-rosas-garden-co": "frontend-breadcrumbs",
    "admin.php?from=1&page=aioseo-seo-revisions&to=3": "admin-seo-revisions",
    "admin.php?notifications=true&page=aioseo": "admin-global--notifications-drawer",
    "admin.php?page=aioseo": "admin-dashboard",
    "admin.php?page=aioseo-about": "admin-about-getting-started",
    "admin.php?page=aioseo-about#/getting-started": "admin-about-getting-started",
    "admin.php?page=aioseo-ai-insights": "admin-ai-insights-keyword-reports",
    "admin.php?page=aioseo-ai-insights#/ai-content": "admin-ai-insights-ai-content",
    "admin.php?page=aioseo-ai-insights#/keyword-reports": "admin-ai-insights-keyword-reports",
    "admin.php?page=aioseo-ai-insights#/mcp": "admin-ai-insights-mcp",
    "admin.php?page=aioseo-feature-manager": "admin-feature-manager",
    "admin.php?page=aioseo-link-assistant": "admin-link-assistant-overview",
    "admin.php?page=aioseo-link-assistant#/domains-report": "admin-link-assistant-domains-report",
    "admin.php?page=aioseo-link-assistant#/domains-report?hostname=extension.oregonstate.edu": "admin-link-assistant-domains-report--hostname",
    "admin.php?page=aioseo-link-assistant#/domains-report?hostname=seedsavers.org": "admin-link-assistant-domains-report--host-seedsavers-org",
    "admin.php?page=aioseo-link-assistant#/domains-report?hostname=xerces.org": "admin-link-assistant-domains-report--host-xerces-org",
    "admin.php?page=aioseo-link-assistant#/links-report": "admin-link-assistant-links-report",
    "admin.php?page=aioseo-link-assistant#/links-report?postTitle=Container+Herbs+for+Beginners": "admin-link-assistant-links-report--search",
    "admin.php?page=aioseo-link-assistant#/links-report?postTitle=Our+Bulb+Planting+Guide+for+Big+Color+Next+Year": "admin-link-assistant-links-report--post-bulb-planting-guide",
    "admin.php?page=aioseo-link-assistant#/links-report?postTitle=Raised+Beds+vs+In-Ground+Gardens:+Which+Is+Right+for+You?": "admin-link-assistant-links-report--post-raised-beds-vs-in-ground",
    "admin.php?page=aioseo-link-assistant#/links-report?postTitle=Watering+Schedules+for+Hot,+Dry+Weeks": "admin-link-assistant-links-report--post-watering-schedules",
    "admin.php?page=aioseo-link-assistant#/links-report?postTitle=When+to+Prune+Hydrangeas+(and+When+to+Leave+Them+Alone)": "admin-link-assistant-links-report--post-when-to-prune-hydrangeas",
    "admin.php?page=aioseo-link-assistant#/overview": "admin-link-assistant-overview",
    "admin.php?page=aioseo-link-assistant#/post-report?postId=2466&postIndex=0&initialTab=inbound-internal": "admin-link-assistant-post-report",
    "admin.php?page=aioseo-link-assistant#/settings": "admin-link-assistant-settings",
    "admin.php?page=aioseo-local-seo": "admin-local-seo-locations",
    "admin.php?page=aioseo-local-seo#/import": "admin-local-seo-import",
    "admin.php?page=aioseo-local-seo#/locations": "admin-local-seo-locations",
    "admin.php?page=aioseo-local-seo#/maps": "admin-local-seo-maps",
    "admin.php?page=aioseo-local-seo#/opening-hours": "admin-local-seo-opening-hours",
    "admin.php?page=aioseo-redirects": "admin-redirects",
    "admin.php?page=aioseo-redirects#/full-site-redirect": "admin-redirects-full-site-redirect",
    "admin.php?page=aioseo-redirects#/http-headers": "admin-redirects-http-headers",
    "admin.php?page=aioseo-redirects#/import-export": "admin-redirects-import-export",
    "admin.php?page=aioseo-redirects#/logs": "admin-redirects-logs",
    "admin.php?page=aioseo-redirects#/redirects": "admin-redirects",
    "admin.php?page=aioseo-redirects#/settings": "admin-redirects-settings",
    "admin.php?page=aioseo-search-appearance": "admin-search-appearance-global-settings",
    "admin.php?page=aioseo-search-appearance#/advanced": "admin-search-appearance-advanced",
    "admin.php?page=aioseo-search-appearance#/archives": "admin-search-appearance-archives",
    "admin.php?page=aioseo-search-appearance#/author-seo": "admin-search-appearance-author-seo",
    "admin.php?page=aioseo-search-appearance#/content-types": "admin-search-appearance-content-types",
    "admin.php?page=aioseo-search-appearance#/global-settings": "admin-search-appearance-global-settings",
    "admin.php?page=aioseo-search-appearance#/media": "admin-search-appearance-media",
    "admin.php?page=aioseo-search-appearance#/taxonomies": "admin-search-appearance-taxonomies",
    "admin.php?page=aioseo-search-statistics": "admin-search-statistics-dashboard",
    "admin.php?page=aioseo-search-statistics#/content-rankings": "admin-search-statistics-content-rankings",
    "admin.php?page=aioseo-search-statistics#/dashboard": "admin-search-statistics-dashboard",
    "admin.php?page=aioseo-search-statistics#/index-status": "admin-search-statistics-index-status",
    "admin.php?page=aioseo-search-statistics#/keyword-rank-tracker": "admin-search-statistics-keyword-rank-tracker",
    "admin.php?page=aioseo-search-statistics#/seo-statistics": "admin-search-statistics-seo-statistics",
    "admin.php?page=aioseo-search-statistics#/settings": "admin-search-statistics-settings",
    "admin.php?page=aioseo-seo-analysis": "admin-seo-analysis-seo-audit-checklist",
    "admin.php?page=aioseo-seo-analysis#/analyze-competitor-site": "admin-seo-analysis-analyze-competitor-site",
    "admin.php?page=aioseo-seo-analysis#/headline-analyzer": "admin-seo-analysis-headline-analyzer",
    "admin.php?page=aioseo-seo-analysis#/seo-audit-checklist": "admin-seo-analysis-seo-audit-checklist",
    "admin.php?page=aioseo-seo-analysis#/seo-site-audit": "admin-seo-analysis-seo-site-audit",
    "admin.php?page=aioseo-seo-analysis#/seo-site-audit?tab=error": "admin-seo-analysis-seo-site-audit",
    "admin.php?page=aioseo-settings": "admin-settings-general",
    "admin.php?page=aioseo-settings#/access-control": "admin-settings-access-control",
    "admin.php?page=aioseo-settings#/advanced": "admin-settings-advanced",
    "admin.php?page=aioseo-settings#/breadcrumbs": "admin-settings-breadcrumbs",
    "admin.php?page=aioseo-settings#/content-optimization": "admin-settings-content-optimization",
    "admin.php?page=aioseo-settings#/general-settings": "admin-settings-general",
    "admin.php?page=aioseo-settings#/rss-content": "admin-settings-rss-content",
    "admin.php?page=aioseo-settings#/seo-checklist": "admin-settings-seo-checklist",
    "admin.php?page=aioseo-settings#/webmaster-tools": "admin-settings-webmaster-tools",
    "admin.php?page=aioseo-sitemaps": "admin-sitemaps-general-sitemap",
    "admin.php?page=aioseo-sitemaps#/general-sitemap": "admin-sitemaps-general-sitemap",
    "admin.php?page=aioseo-sitemaps#/html-sitemap": "admin-sitemaps-html-sitemap",
    "admin.php?page=aioseo-sitemaps#/llms-sitemap": "admin-sitemaps-llms-sitemap",
    "admin.php?page=aioseo-sitemaps#/news-sitemap": "admin-sitemaps-news-sitemap",
    "admin.php?page=aioseo-sitemaps#/rss-sitemap": "admin-sitemaps-rss-sitemap",
    "admin.php?page=aioseo-sitemaps#/video-sitemap": "admin-sitemaps-video-sitemap",
    "admin.php?page=aioseo-social-networks": "admin-social-networks-social-profiles",
    "admin.php?page=aioseo-social-networks#/facebook": "admin-social-networks-facebook",
    "admin.php?page=aioseo-social-networks#/pinterest": "admin-social-networks-pinterest",
    "admin.php?page=aioseo-social-networks#/social-profiles": "admin-social-networks-social-profiles",
    "admin.php?page=aioseo-social-networks#/twitter": "admin-social-networks-twitter",
    "admin.php?page=aioseo-tools": "admin-tools-robots-editor",
    "admin.php?page=aioseo-tools#/database-tools": "admin-tools-database-tools",
    "admin.php?page=aioseo-tools#/import-export": "admin-tools-import-export",
    "admin.php?page=aioseo-tools#/robots-editor": "admin-tools-robots-editor",
    "admin.php?page=aioseo-tools#/seo-alerts": "admin-tools-seo-alerts",
    "admin.php?page=aioseo-tools#/snippets": "admin-tools-snippets",
    "admin.php?page=aioseo-tools#/system-status": "admin-tools-system-status",
    "bulb-planting-guide": "frontend-bulb-planting-guide",
    "composting-101": "frontend-composting-101",
    "container-herbs-for-beginners": "frontend-container-herbs-for-beginners",
    "eastside-garden-center": "frontend-location-eastside-garden-center",
    "edit-tags.php?taxonomy=category": "admin-edit-tags-category",
    "edit.php": "admin-edit-posts",
    "edit.php?all_posts=1&post_type=post": "admin-edit-posts",
    "edit.php?post_type=aioseo-location": "admin-locations-list",
    "edit.php?post_type=page": "admin-edit-pages",
    "free-composting-workshop": "frontend-free-composting-workshop",
    "fruit-trees-small-yards": "frontend-fruit-trees-small-yards",
    "garden-design-services": "frontend-page-garden-design-services",
    "garden-tools-cold-weather": "frontend-garden-tools-cold-weather",
    "hillcrest-design-studio": "frontend-location-hillcrest-design-studio",
    "holiday-hours": "frontend-holiday-hours",
    "index.php": "admin-dashboard-widgets",
    "index.php?page=aioseo-setup-wizard#/additional-information": "wizard-additional-information",
    "index.php?page=aioseo-setup-wizard#/category": "wizard-category",
    "index.php?page=aioseo-setup-wizard#/features": "wizard-features",
    "index.php?page=aioseo-setup-wizard#/import": "wizard-import",
    "index.php?page=aioseo-setup-wizard#/search-appearance": "wizard-search-appearance",
    "index.php?page=aioseo-setup-wizard#/search-console": "wizard-search-console",
    "index.php?page=aioseo-setup-wizard#/success": "wizard-success",
    "index.php?page=aioseo-setup-wizard#/welcome": "wizard-welcome",
    "index.php?snap-sitemap=index": "frontend-sitemap-index",
    "index.php?snap-sitemap=page": "frontend-sitemap-page",
    "index.php?snap-sitemap=post": "frontend-sitemap-post",
    "native-plants-for-pollinators": "frontend-native-plants-for-pollinators",
    "nursery-plant-care-faq": "frontend-nursery-plant-care-faq",
    "page-sitemap.xml": "frontend-sitemap-page",
    "plan-a-vegetable-bed": "frontend-author-bio",
    "post-new.php": "editor-post--score-none",
    "post-sitemap.xml": "frontend-sitemap-post",
    "post.php?action=edit&post=2466": "editor-post",
    "post.php?action=edit&post=2467": "editor-post-p-shade-loving-perennials",
    "post.php?action=edit&post=2468": "editor-post--score-green",
    "post.php?action=edit&post=2469": "editor-post-p-when-to-prune-hydrangeas",
    "post.php?action=edit&post=2470": "editor-post-p-native-plants-for-pollinators",
    "post.php?action=edit&post=2471": "editor-post-p-raised-beds-vs-in-ground",
    "post.php?action=edit&post=2472": "editor-post-p-bulb-planting-guide",
    "post.php?action=edit&post=2473": "editor-post-p-watering-schedules",
    "post.php?action=edit&post=2474": "editor-post-p-container-herbs-for-beginners",
    "post.php?action=edit&post=2475": "editor-post-p-garden-tools-cold-weather",
    "post.php?action=edit&post=2476": "editor-post-p-second-nursery-east-side",
    "post.php?action=edit&post=2477": "editor-post-p-free-composting-workshop",
    "post.php?action=edit&post=2478": "editor-post-p-planning-seed-orders",
    "post.php?action=edit&post=2479": "editor-page-about-rosas-garden-co",
    "post.php?action=edit&post=2480": "editor-page-garden-design-services",
    "post.php?action=edit&post=2481": "editor-page-visit-our-nurseries",
    "post.php?action=edit&post=2482": "editor-page-site-map",
    "post.php?action=edit&post=2485": "editor-location",
    "post.php?action=edit&post=2486": "editor-location-eastside-garden-center",
    "post.php?action=edit&post=2487": "editor-location-hillcrest-design-studio",
    "post.php?action=edit&post=2491": "editor-post-block-faq",
    "post.php?action=edit&post=2492": "editor-classic-post",
    "post.php?action=edit&post=2506": "editor-post-p-holiday-hours",
    "profile.php": "admin-profile-aioseo",
    "profile.php?snap=50": "admin-profile-aioseo--add-item",
    "raised-beds-vs-in-ground": "frontend-raised-beds-vs-in-ground",
    "riverside-nursery": "frontend-location-riverside-nursery",
    "second-nursery-east-side": "frontend-second-nursery-east-side",
    "shade-loving-perennials": "frontend-shade-loving-perennials",
    "site-map": "frontend-html-sitemap",
    "sitemap.xml": "frontend-sitemap-index",
    "term.php?tag_ID=31&taxonomy=category": "admin-term-edit",
    "visit-our-nurseries": "frontend-local-business",
    "watering-schedules": "frontend-watering-schedules",
    "when-to-prune-hydrangeas": "frontend-when-to-prune-hydrangeas"
  },
  "v": {
    "admin.php?page=aioseo": [
      "notifications"
    ],
    "admin.php?page=aioseo-link-assistant#/post-report?postId=2466": [
      "initialTab",
      "postIndex"
    ],
    "admin.php?page=aioseo-seo-revisions": [
      "from",
      "to"
    ],
    "edit-tags.php": [
      "taxonomy"
    ],
    "edit.php": [
      "all_posts",
      "post_type"
    ],
    "index.php": [
      "snap-sitemap"
    ],
    "post.php": [
      "action",
      "post"
    ],
    "profile.php": [
      "snap"
    ],
    "term.php": [
      "tag_ID",
      "taxonomy"
    ]
  },
  "r": [
    {
      "page": "admin.php?page=aioseo-about",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-ai-insights",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-link-assistant",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-local-seo",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-redirects",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-search-appearance",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-search-statistics",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-seo-analysis",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-settings",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-sitemaps",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-social-networks",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "admin.php?page=aioseo-tools",
      "drop": [
        "snap"
      ]
    },
    {
      "page": "index.php?page=aioseo-setup-wizard",
      "drop": [
        "snap"
      ]
    }
  ]
};
